// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbase_add.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBase_add_CfgInitialize(XBase_add *InstancePtr, XBase_add_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_BaseAddress = ConfigPtr->Ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBase_add_Start(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL) & 0x80;
    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBase_add_IsDone(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBase_add_IsIdle(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBase_add_IsReady(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBase_add_EnableAutoRestart(XBase_add *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL, 0x80);
}

void XBase_add_DisableAutoRestart(XBase_add *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_AP_CTRL, 0);
}

void XBase_add_Set_buffer_r(XBase_add *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_BUFFER_R_DATA, Data);
}

u32 XBase_add_Get_buffer_r(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_BUFFER_R_DATA);
    return Data;
}

void XBase_add_Set_sample_count(XBase_add *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_SAMPLE_COUNT_DATA, Data);
}

u32 XBase_add_Get_sample_count(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_SAMPLE_COUNT_DATA);
    return Data;
}

void XBase_add_Set_capture_mode(XBase_add *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_CAPTURE_MODE_DATA, Data);
}

u32 XBase_add_Get_capture_mode(XBase_add *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_CAPTURE_MODE_DATA);
    return Data;
}

void XBase_add_InterruptGlobalEnable(XBase_add *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_GIE, 1);
}

void XBase_add_InterruptGlobalDisable(XBase_add *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_GIE, 0);
}

void XBase_add_InterruptEnable(XBase_add *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_IER);
    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_IER, Register | Mask);
}

void XBase_add_InterruptDisable(XBase_add *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_IER);
    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_IER, Register & (~Mask));
}

void XBase_add_InterruptClear(XBase_add *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBase_add_WriteReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_ISR, Mask);
}

u32 XBase_add_InterruptGetEnabled(XBase_add *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_IER);
}

u32 XBase_add_InterruptGetStatus(XBase_add *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBase_add_ReadReg(InstancePtr->Ctrl_BaseAddress, XBASE_ADD_CTRL_ADDR_ISR);
}

