// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="base_add,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=65545,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=986,HLS_SYN_LUT=1354,HLS_VERSION=2018_2}" *)

module base_add (
        ap_clk,
        ap_rst_n,
        m_axi_GMEM_AWVALID,
        m_axi_GMEM_AWREADY,
        m_axi_GMEM_AWADDR,
        m_axi_GMEM_AWID,
        m_axi_GMEM_AWLEN,
        m_axi_GMEM_AWSIZE,
        m_axi_GMEM_AWBURST,
        m_axi_GMEM_AWLOCK,
        m_axi_GMEM_AWCACHE,
        m_axi_GMEM_AWPROT,
        m_axi_GMEM_AWQOS,
        m_axi_GMEM_AWREGION,
        m_axi_GMEM_AWUSER,
        m_axi_GMEM_WVALID,
        m_axi_GMEM_WREADY,
        m_axi_GMEM_WDATA,
        m_axi_GMEM_WSTRB,
        m_axi_GMEM_WLAST,
        m_axi_GMEM_WID,
        m_axi_GMEM_WUSER,
        m_axi_GMEM_ARVALID,
        m_axi_GMEM_ARREADY,
        m_axi_GMEM_ARADDR,
        m_axi_GMEM_ARID,
        m_axi_GMEM_ARLEN,
        m_axi_GMEM_ARSIZE,
        m_axi_GMEM_ARBURST,
        m_axi_GMEM_ARLOCK,
        m_axi_GMEM_ARCACHE,
        m_axi_GMEM_ARPROT,
        m_axi_GMEM_ARQOS,
        m_axi_GMEM_ARREGION,
        m_axi_GMEM_ARUSER,
        m_axi_GMEM_RVALID,
        m_axi_GMEM_RREADY,
        m_axi_GMEM_RDATA,
        m_axi_GMEM_RLAST,
        m_axi_GMEM_RID,
        m_axi_GMEM_RUSER,
        m_axi_GMEM_RRESP,
        m_axi_GMEM_BVALID,
        m_axi_GMEM_BREADY,
        m_axi_GMEM_BRESP,
        m_axi_GMEM_BID,
        m_axi_GMEM_BUSER,
        sample_stream_V_V_TDATA,
        sample_stream_V_V_TVALID,
        sample_stream_V_V_TREADY,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state12 = 4'd8;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_GMEM_AWVALID;
input   m_axi_GMEM_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_GMEM_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_GMEM_AWID;
output  [7:0] m_axi_GMEM_AWLEN;
output  [2:0] m_axi_GMEM_AWSIZE;
output  [1:0] m_axi_GMEM_AWBURST;
output  [1:0] m_axi_GMEM_AWLOCK;
output  [3:0] m_axi_GMEM_AWCACHE;
output  [2:0] m_axi_GMEM_AWPROT;
output  [3:0] m_axi_GMEM_AWQOS;
output  [3:0] m_axi_GMEM_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_GMEM_AWUSER;
output   m_axi_GMEM_WVALID;
input   m_axi_GMEM_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_GMEM_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_GMEM_WSTRB;
output   m_axi_GMEM_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_GMEM_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_GMEM_WUSER;
output   m_axi_GMEM_ARVALID;
input   m_axi_GMEM_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_GMEM_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_GMEM_ARID;
output  [7:0] m_axi_GMEM_ARLEN;
output  [2:0] m_axi_GMEM_ARSIZE;
output  [1:0] m_axi_GMEM_ARBURST;
output  [1:0] m_axi_GMEM_ARLOCK;
output  [3:0] m_axi_GMEM_ARCACHE;
output  [2:0] m_axi_GMEM_ARPROT;
output  [3:0] m_axi_GMEM_ARQOS;
output  [3:0] m_axi_GMEM_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_GMEM_ARUSER;
input   m_axi_GMEM_RVALID;
output   m_axi_GMEM_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_GMEM_RDATA;
input   m_axi_GMEM_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_GMEM_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_GMEM_RUSER;
input  [1:0] m_axi_GMEM_RRESP;
input   m_axi_GMEM_BVALID;
output   m_axi_GMEM_BREADY;
input  [1:0] m_axi_GMEM_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_GMEM_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_GMEM_BUSER;
input  [31:0] sample_stream_V_V_TDATA;
input   sample_stream_V_V_TVALID;
output   sample_stream_V_V_TREADY;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] buffer_r;
wire   [31:0] sample_count;
wire   [31:0] capture_mode;
reg   [31:0] sample_stream_V_V_0_data_out;
wire    sample_stream_V_V_0_vld_in;
wire    sample_stream_V_V_0_vld_out;
wire    sample_stream_V_V_0_ack_in;
reg    sample_stream_V_V_0_ack_out;
reg   [31:0] sample_stream_V_V_0_payload_A;
reg   [31:0] sample_stream_V_V_0_payload_B;
reg    sample_stream_V_V_0_sel_rd;
reg    sample_stream_V_V_0_sel_wr;
wire    sample_stream_V_V_0_sel;
wire    sample_stream_V_V_0_load_A;
wire    sample_stream_V_V_0_load_B;
reg   [1:0] sample_stream_V_V_0_state;
wire    sample_stream_V_V_0_state_cmp_full;
reg    GMEM_blk_n_AW;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_reg_387;
reg    GMEM_blk_n_W;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] exitcond_reg_387_pp0_iter1_reg;
reg    GMEM_blk_n_B;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] exitcond_reg_387_pp0_iter3_reg;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] exitcond_reg_387_pp0_iter4_reg;
reg    sample_stream_V_V_TDATA_blk_n;
reg   [0:0] tmp_2_reg_383;
reg    GMEM_AWVALID;
wire    GMEM_AWREADY;
reg   [31:0] GMEM_AWADDR;
reg    GMEM_WVALID;
wire    GMEM_WREADY;
reg   [31:0] GMEM_WDATA;
wire    GMEM_ARREADY;
wire    GMEM_RVALID;
wire   [31:0] GMEM_RDATA;
wire    GMEM_RLAST;
wire   [0:0] GMEM_RID;
wire   [0:0] GMEM_RUSER;
wire   [1:0] GMEM_RRESP;
wire    GMEM_BVALID;
reg    GMEM_BREADY;
wire   [1:0] GMEM_BRESP;
wire   [0:0] GMEM_BID;
wire   [0:0] GMEM_BUSER;
reg   [16:0] i_reg_158;
reg   [11:0] ch2_reg_179;
wire   [30:0] tmp_3_cast_fu_199_p1;
reg   [30:0] tmp_3_cast_reg_372;
wire   [16:0] n_1_fu_231_p3;
reg   [16:0] n_1_reg_378;
wire   [0:0] tmp_2_fu_239_p2;
wire   [0:0] exitcond_fu_245_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op50_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_sig_ioackin_GMEM_AWREADY;
reg    ap_block_state4_io;
wire    ap_block_state6_pp0_stage0_iter2;
reg    ap_sig_ioackin_GMEM_WREADY;
reg    ap_block_state6_io;
wire    ap_block_state8_pp0_stage0_iter3;
reg    ap_block_state10_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_reg_387_pp0_iter2_reg;
wire   [16:0] i_1_fu_250_p2;
reg   [16:0] i_1_reg_391;
reg    ap_enable_reg_pp0_iter0;
wire   [30:0] buffer2_sum_fu_260_p2;
reg   [30:0] buffer2_sum_reg_396;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
reg    ap_block_state5_io;
wire    ap_block_state7_pp0_stage1_iter2;
wire    ap_block_state9_pp0_stage1_iter3;
reg    ap_block_state11_pp0_stage1_iter4;
reg    ap_block_pp0_stage1_11001;
wire   [11:0] tri_3_fu_291_p3;
wire   [11:0] tmp_11_fu_299_p1;
wire   [11:0] tmp_9_fu_323_p1;
wire   [30:0] buffer2_sum3_fu_347_p2;
reg   [30:0] buffer2_sum3_reg_427;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter3;
reg   [16:0] ap_phi_mux_i_phi_fu_162_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_ch_reg_170;
reg   [11:0] ap_phi_reg_pp0_iter1_ch_reg_170;
wire   [11:0] ap_phi_reg_pp0_iter0_ch2_reg_179;
reg   [11:0] ap_phi_reg_pp0_iter1_ch2_reg_179;
wire   [63:0] buffer2_sum_cast_fu_327_p1;
wire   [63:0] buffer2_sum3_cast_fu_357_p1;
reg    ap_reg_ioackin_GMEM_AWREADY;
reg    ap_block_pp0_stage0_01001;
reg    ap_reg_ioackin_GMEM_WREADY;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] ch_cast_fu_352_p1;
wire   [31:0] ch2_cast_fu_367_p1;
wire   [29:0] tmp_3_fu_189_p4;
wire   [0:0] tmp_fu_203_p2;
wire   [30:0] tmp_4_fu_209_p1;
wire   [30:0] p_sample_count_fu_213_p3;
wire   [0:0] tmp_1_fu_225_p2;
wire   [16:0] tmp_7_fu_221_p1;
wire   [30:0] tmp_cast_fu_256_p1;
wire   [7:0] phase_fu_265_p1;
wire   [11:0] tri_fu_277_p3;
wire   [0:0] tmp_10_fu_269_p3;
wire   [11:0] tri_1_fu_285_p2;
wire   [10:0] p_lshr_f_fu_313_p4;
wire   [16:0] tmp_5_fu_337_p2;
wire   [30:0] tmp_7_cast_fu_343_p1;
wire    ap_CS_fsm_state12;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_658;
reg    ap_condition_662;
reg    ap_condition_469;
reg    ap_condition_486;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 sample_stream_V_V_0_sel_rd = 1'b0;
#0 sample_stream_V_V_0_sel_wr = 1'b0;
#0 sample_stream_V_V_0_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_reg_ioackin_GMEM_AWREADY = 1'b0;
#0 ap_reg_ioackin_GMEM_WREADY = 1'b0;
end

base_add_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
base_add_CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .buffer_r(buffer_r),
    .sample_count(sample_count),
    .capture_mode(capture_mode)
);

base_add_GMEM_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
base_add_GMEM_m_axi_U(
    .AWVALID(m_axi_GMEM_AWVALID),
    .AWREADY(m_axi_GMEM_AWREADY),
    .AWADDR(m_axi_GMEM_AWADDR),
    .AWID(m_axi_GMEM_AWID),
    .AWLEN(m_axi_GMEM_AWLEN),
    .AWSIZE(m_axi_GMEM_AWSIZE),
    .AWBURST(m_axi_GMEM_AWBURST),
    .AWLOCK(m_axi_GMEM_AWLOCK),
    .AWCACHE(m_axi_GMEM_AWCACHE),
    .AWPROT(m_axi_GMEM_AWPROT),
    .AWQOS(m_axi_GMEM_AWQOS),
    .AWREGION(m_axi_GMEM_AWREGION),
    .AWUSER(m_axi_GMEM_AWUSER),
    .WVALID(m_axi_GMEM_WVALID),
    .WREADY(m_axi_GMEM_WREADY),
    .WDATA(m_axi_GMEM_WDATA),
    .WSTRB(m_axi_GMEM_WSTRB),
    .WLAST(m_axi_GMEM_WLAST),
    .WID(m_axi_GMEM_WID),
    .WUSER(m_axi_GMEM_WUSER),
    .ARVALID(m_axi_GMEM_ARVALID),
    .ARREADY(m_axi_GMEM_ARREADY),
    .ARADDR(m_axi_GMEM_ARADDR),
    .ARID(m_axi_GMEM_ARID),
    .ARLEN(m_axi_GMEM_ARLEN),
    .ARSIZE(m_axi_GMEM_ARSIZE),
    .ARBURST(m_axi_GMEM_ARBURST),
    .ARLOCK(m_axi_GMEM_ARLOCK),
    .ARCACHE(m_axi_GMEM_ARCACHE),
    .ARPROT(m_axi_GMEM_ARPROT),
    .ARQOS(m_axi_GMEM_ARQOS),
    .ARREGION(m_axi_GMEM_ARREGION),
    .ARUSER(m_axi_GMEM_ARUSER),
    .RVALID(m_axi_GMEM_RVALID),
    .RREADY(m_axi_GMEM_RREADY),
    .RDATA(m_axi_GMEM_RDATA),
    .RLAST(m_axi_GMEM_RLAST),
    .RID(m_axi_GMEM_RID),
    .RUSER(m_axi_GMEM_RUSER),
    .RRESP(m_axi_GMEM_RRESP),
    .BVALID(m_axi_GMEM_BVALID),
    .BREADY(m_axi_GMEM_BREADY),
    .BRESP(m_axi_GMEM_BRESP),
    .BID(m_axi_GMEM_BID),
    .BUSER(m_axi_GMEM_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(GMEM_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(GMEM_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(GMEM_RDATA),
    .I_RID(GMEM_RID),
    .I_RUSER(GMEM_RUSER),
    .I_RRESP(GMEM_RRESP),
    .I_RLAST(GMEM_RLAST),
    .I_AWVALID(GMEM_AWVALID),
    .I_AWREADY(GMEM_AWREADY),
    .I_AWADDR(GMEM_AWADDR),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(GMEM_WVALID),
    .I_WREADY(GMEM_WREADY),
    .I_WDATA(GMEM_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(GMEM_BVALID),
    .I_BREADY(GMEM_BREADY),
    .I_BRESP(GMEM_BRESP),
    .I_BID(GMEM_BID),
    .I_BUSER(GMEM_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_GMEM_AWREADY <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0)))) begin
            ap_reg_ioackin_GMEM_AWREADY <= 1'b0;
        end else if ((((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == GMEM_AWREADY) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_01001) & (1'b1 == GMEM_AWREADY) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0)))) begin
            ap_reg_ioackin_GMEM_AWREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_GMEM_WREADY <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)))) begin
            ap_reg_ioackin_GMEM_WREADY <= 1'b0;
        end else if ((((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == GMEM_WREADY) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_01001) & (1'b1 == GMEM_WREADY) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)))) begin
            ap_reg_ioackin_GMEM_WREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        sample_stream_V_V_0_sel_rd <= 1'b0;
    end else begin
        if (((sample_stream_V_V_0_ack_out == 1'b1) & (sample_stream_V_V_0_vld_out == 1'b1))) begin
            sample_stream_V_V_0_sel_rd <= ~sample_stream_V_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        sample_stream_V_V_0_sel_wr <= 1'b0;
    end else begin
        if (((sample_stream_V_V_0_ack_in == 1'b1) & (sample_stream_V_V_0_vld_in == 1'b1))) begin
            sample_stream_V_V_0_sel_wr <= ~sample_stream_V_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        sample_stream_V_V_0_state <= 2'd0;
    end else begin
        if ((((sample_stream_V_V_0_state == 2'd2) & (sample_stream_V_V_0_vld_in == 1'b0)) | ((sample_stream_V_V_0_state == 2'd3) & (sample_stream_V_V_0_vld_in == 1'b0) & (sample_stream_V_V_0_ack_out == 1'b1)))) begin
            sample_stream_V_V_0_state <= 2'd2;
        end else if ((((sample_stream_V_V_0_state == 2'd1) & (sample_stream_V_V_0_ack_out == 1'b0)) | ((sample_stream_V_V_0_state == 2'd3) & (sample_stream_V_V_0_ack_out == 1'b0) & (sample_stream_V_V_0_vld_in == 1'b1)))) begin
            sample_stream_V_V_0_state <= 2'd1;
        end else if (((~((sample_stream_V_V_0_vld_in == 1'b0) & (sample_stream_V_V_0_ack_out == 1'b1)) & ~((sample_stream_V_V_0_ack_out == 1'b0) & (sample_stream_V_V_0_vld_in == 1'b1)) & (sample_stream_V_V_0_state == 2'd3)) | ((sample_stream_V_V_0_state == 2'd1) & (sample_stream_V_V_0_ack_out == 1'b1)) | ((sample_stream_V_V_0_state == 2'd2) & (sample_stream_V_V_0_vld_in == 1'b1)))) begin
            sample_stream_V_V_0_state <= 2'd3;
        end else begin
            sample_stream_V_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_383 == 1'd0) & (exitcond_reg_387 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_ch2_reg_179 <= {{sample_stream_V_V_0_data_out[27:16]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_383 == 1'd1) & (exitcond_reg_387 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_ch2_reg_179 <= tmp_9_fu_323_p1;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_ch2_reg_179 <= ap_phi_reg_pp0_iter0_ch2_reg_179;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_383 == 1'd0) & (exitcond_reg_387 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_ch_reg_170 <= tmp_11_fu_299_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_2_reg_383 == 1'd1) & (exitcond_reg_387 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_ch_reg_170 <= tri_3_fu_291_p3;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_phi_reg_pp0_iter1_ch_reg_170 <= ap_phi_reg_pp0_iter0_ch_reg_170;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0))) begin
        i_reg_158 <= i_1_reg_391;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_158 <= 17'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0))) begin
        buffer2_sum3_reg_427 <= buffer2_sum3_fu_347_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_reg_387 == 1'd0))) begin
        buffer2_sum_reg_396 <= buffer2_sum_fu_260_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ch2_reg_179 <= ap_phi_reg_pp0_iter1_ch2_reg_179;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_reg_387 <= exitcond_fu_245_p2;
        exitcond_reg_387_pp0_iter1_reg <= exitcond_reg_387;
        exitcond_reg_387_pp0_iter2_reg <= exitcond_reg_387_pp0_iter1_reg;
        exitcond_reg_387_pp0_iter3_reg <= exitcond_reg_387_pp0_iter2_reg;
        exitcond_reg_387_pp0_iter4_reg <= exitcond_reg_387_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_391 <= i_1_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_1_reg_378 <= n_1_fu_231_p3;
        tmp_2_reg_383 <= tmp_2_fu_239_p2;
        tmp_3_cast_reg_372[29 : 0] <= tmp_3_cast_fu_199_p1[29 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((sample_stream_V_V_0_load_A == 1'b1)) begin
        sample_stream_V_V_0_payload_A <= sample_stream_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((sample_stream_V_V_0_load_B == 1'b1)) begin
        sample_stream_V_V_0_payload_B <= sample_stream_V_V_TDATA;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_GMEM_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        if ((1'b1 == ap_condition_662)) begin
            GMEM_AWADDR = buffer2_sum3_cast_fu_357_p1;
        end else if ((1'b1 == ap_condition_658)) begin
            GMEM_AWADDR = buffer2_sum_cast_fu_327_p1;
        end else begin
            GMEM_AWADDR = 'bx;
        end
    end else begin
        GMEM_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_reg_ioackin_GMEM_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_reg_ioackin_GMEM_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0)))) begin
        GMEM_AWVALID = 1'b1;
    end else begin
        GMEM_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_reg_387_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387_pp0_iter3_reg == 1'd0)))) begin
        GMEM_BREADY = 1'b1;
    end else begin
        GMEM_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_GMEM_WREADY == 1'b0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0))) begin
        if ((1'b1 == ap_condition_486)) begin
            GMEM_WDATA = ch2_cast_fu_367_p1;
        end else if ((1'b1 == ap_condition_469)) begin
            GMEM_WDATA = ch_cast_fu_352_p1;
        end else begin
            GMEM_WDATA = 'bx;
        end
    end else begin
        GMEM_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_reg_ioackin_GMEM_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_reg_ioackin_GMEM_WREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)))) begin
        GMEM_WVALID = 1'b1;
    end else begin
        GMEM_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (exitcond_reg_387 == 1'd0)))) begin
        GMEM_blk_n_AW = m_axi_GMEM_AWREADY;
    end else begin
        GMEM_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (exitcond_reg_387_pp0_iter4_reg == 1'd0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (exitcond_reg_387_pp0_iter3_reg == 1'd0)))) begin
        GMEM_blk_n_B = m_axi_GMEM_BVALID;
    end else begin
        GMEM_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)))) begin
        GMEM_blk_n_W = m_axi_GMEM_WREADY;
    end else begin
        GMEM_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_fu_245_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (exitcond_reg_387 == 1'd0))) begin
        ap_phi_mux_i_phi_fu_162_p4 = i_1_reg_391;
    end else begin
        ap_phi_mux_i_phi_fu_162_p4 = i_reg_158;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_GMEM_AWREADY == 1'b0)) begin
        ap_sig_ioackin_GMEM_AWREADY = GMEM_AWREADY;
    end else begin
        ap_sig_ioackin_GMEM_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_GMEM_WREADY == 1'b0)) begin
        ap_sig_ioackin_GMEM_WREADY = GMEM_WREADY;
    end else begin
        ap_sig_ioackin_GMEM_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op50_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sample_stream_V_V_0_ack_out = 1'b1;
    end else begin
        sample_stream_V_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((sample_stream_V_V_0_sel == 1'b1)) begin
        sample_stream_V_V_0_data_out = sample_stream_V_V_0_payload_B;
    end else begin
        sample_stream_V_V_0_data_out = sample_stream_V_V_0_payload_A;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (tmp_2_reg_383 == 1'd0) & (exitcond_reg_387 == 1'd0))) begin
        sample_stream_V_V_TDATA_blk_n = sample_stream_V_V_0_state[1'd0];
    end else begin
        sample_stream_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_fu_245_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_fu_245_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter3_reg == 1'd0)) | ((sample_stream_V_V_0_vld_out == 1'b0) & (ap_predicate_op50_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter3_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((sample_stream_V_V_0_vld_out == 1'b0) & (ap_predicate_op50_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter3_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state4_io) | ((sample_stream_V_V_0_vld_out == 1'b0) & (ap_predicate_op50_read_state4 == 1'b1)))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter4_reg == 1'd0)) | ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b0 == GMEM_BVALID) & (ap_enable_reg_pp0_iter4 == 1'b1) & (exitcond_reg_387_pp0_iter4_reg == 1'd0)) | ((1'b1 == ap_block_state5_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter4 = ((1'b0 == GMEM_BVALID) & (exitcond_reg_387_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_block_state11_pp0_stage1_iter4 = ((1'b0 == GMEM_BVALID) & (exitcond_reg_387_pp0_iter4_reg == 1'd0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_io = ((ap_sig_ioackin_GMEM_AWREADY == 1'b0) & (exitcond_reg_387 == 1'd0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((sample_stream_V_V_0_vld_out == 1'b0) & (ap_predicate_op50_read_state4 == 1'b1));
end

always @ (*) begin
    ap_block_state5_io = (((ap_sig_ioackin_GMEM_WREADY == 1'b0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)) | ((ap_sig_ioackin_GMEM_AWREADY == 1'b0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0)));
end

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((ap_sig_ioackin_GMEM_WREADY == 1'b0) & (exitcond_reg_387_pp0_iter1_reg == 1'd0));
end

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_469 = ((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_486 = ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_658 = ((1'b0 == ap_block_pp0_stage0_01001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_reg_387 == 1'd0));
end

always @ (*) begin
    ap_condition_662 = ((1'b0 == ap_block_pp0_stage1_01001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_reg_387_pp0_iter1_reg == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_ch2_reg_179 = 'bx;

assign ap_phi_reg_pp0_iter0_ch_reg_170 = 'bx;

always @ (*) begin
    ap_predicate_op50_read_state4 = ((tmp_2_reg_383 == 1'd0) & (exitcond_reg_387 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign buffer2_sum3_cast_fu_357_p1 = buffer2_sum3_reg_427;

assign buffer2_sum3_fu_347_p2 = (tmp_7_cast_fu_343_p1 + tmp_3_cast_reg_372);

assign buffer2_sum_cast_fu_327_p1 = buffer2_sum_reg_396;

assign buffer2_sum_fu_260_p2 = (tmp_cast_fu_256_p1 + tmp_3_cast_reg_372);

assign ch2_cast_fu_367_p1 = ch2_reg_179;

assign ch_cast_fu_352_p1 = ap_phi_reg_pp0_iter1_ch_reg_170;

assign exitcond_fu_245_p2 = ((ap_phi_mux_i_phi_fu_162_p4 == n_1_reg_378) ? 1'b1 : 1'b0);

assign i_1_fu_250_p2 = (ap_phi_mux_i_phi_fu_162_p4 + 17'd1);

assign n_1_fu_231_p3 = ((tmp_1_fu_225_p2[0:0] === 1'b1) ? 17'd65536 : tmp_7_fu_221_p1);

assign p_lshr_f_fu_313_p4 = {{tri_3_fu_291_p3[11:1]}};

assign p_sample_count_fu_213_p3 = ((tmp_fu_203_p2[0:0] === 1'b1) ? 31'd1 : tmp_4_fu_209_p1);

assign phase_fu_265_p1 = i_reg_158[7:0];

assign sample_stream_V_V_0_ack_in = sample_stream_V_V_0_state[1'd1];

assign sample_stream_V_V_0_load_A = (sample_stream_V_V_0_state_cmp_full & ~sample_stream_V_V_0_sel_wr);

assign sample_stream_V_V_0_load_B = (sample_stream_V_V_0_state_cmp_full & sample_stream_V_V_0_sel_wr);

assign sample_stream_V_V_0_sel = sample_stream_V_V_0_sel_rd;

assign sample_stream_V_V_0_state_cmp_full = ((sample_stream_V_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign sample_stream_V_V_0_vld_in = sample_stream_V_V_TVALID;

assign sample_stream_V_V_0_vld_out = sample_stream_V_V_0_state[1'd0];

assign sample_stream_V_V_TREADY = sample_stream_V_V_0_state[1'd1];

assign tmp_10_fu_269_p3 = i_reg_158[32'd7];

assign tmp_11_fu_299_p1 = sample_stream_V_V_0_data_out[11:0];

assign tmp_1_fu_225_p2 = ((p_sample_count_fu_213_p3 > 31'd65536) ? 1'b1 : 1'b0);

assign tmp_2_fu_239_p2 = ((capture_mode == 32'd0) ? 1'b1 : 1'b0);

assign tmp_3_cast_fu_199_p1 = tmp_3_fu_189_p4;

assign tmp_3_fu_189_p4 = {{buffer_r[31:2]}};

assign tmp_4_fu_209_p1 = sample_count[30:0];

assign tmp_5_fu_337_p2 = (i_reg_158 ^ 17'd65536);

assign tmp_7_cast_fu_343_p1 = tmp_5_fu_337_p2;

assign tmp_7_fu_221_p1 = p_sample_count_fu_213_p3[16:0];

assign tmp_9_fu_323_p1 = p_lshr_f_fu_313_p4;

assign tmp_cast_fu_256_p1 = i_reg_158;

assign tmp_fu_203_p2 = (($signed(sample_count) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign tri_1_fu_285_p2 = (tri_fu_277_p3 ^ 12'd4080);

assign tri_3_fu_291_p3 = ((tmp_10_fu_269_p3[0:0] === 1'b1) ? tri_1_fu_285_p2 : tri_fu_277_p3);

assign tri_fu_277_p3 = {{phase_fu_265_p1}, {4'd0}};

always @ (posedge ap_clk) begin
    tmp_3_cast_reg_372[30] <= 1'b0;
end

endmodule //base_add
