// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "base_add.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic base_add::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic base_add::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> base_add::ap_ST_fsm_state1 = "1";
const sc_lv<4> base_add::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<4> base_add::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<4> base_add::ap_ST_fsm_state12 = "1000";
const sc_lv<32> base_add::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool base_add::ap_const_boolean_1 = true;
const sc_lv<1> base_add::ap_const_lv1_0 = "0";
const sc_lv<1> base_add::ap_const_lv1_1 = "1";
const sc_lv<2> base_add::ap_const_lv2_0 = "00";
const sc_lv<2> base_add::ap_const_lv2_2 = "10";
const sc_lv<2> base_add::ap_const_lv2_3 = "11";
const sc_lv<2> base_add::ap_const_lv2_1 = "1";
const sc_lv<32> base_add::ap_const_lv32_1 = "1";
const bool base_add::ap_const_boolean_0 = false;
const sc_lv<32> base_add::ap_const_lv32_2 = "10";
const int base_add::C_S_AXI_DATA_WIDTH = "100000";
const int base_add::C_M_AXI_GMEM_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int base_add::C_M_AXI_GMEM_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int base_add::C_M_AXI_GMEM_CACHE_VALUE = "11";
const int base_add::C_M_AXI_DATA_WIDTH = "100000";
const sc_lv<17> base_add::ap_const_lv17_0 = "00000000000000000";
const sc_lv<3> base_add::ap_const_lv3_0 = "000";
const sc_lv<4> base_add::ap_const_lv4_0 = "0000";
const sc_lv<4> base_add::ap_const_lv4_F = "1111";
const sc_lv<32> base_add::ap_const_lv32_1F = "11111";
const sc_lv<31> base_add::ap_const_lv31_1 = "1";
const sc_lv<31> base_add::ap_const_lv31_10000 = "10000000000000000";
const sc_lv<17> base_add::ap_const_lv17_10000 = "10000000000000000";
const sc_lv<17> base_add::ap_const_lv17_1 = "1";
const sc_lv<32> base_add::ap_const_lv32_7 = "111";
const sc_lv<12> base_add::ap_const_lv12_FF0 = "111111110000";
const sc_lv<32> base_add::ap_const_lv32_10 = "10000";
const sc_lv<32> base_add::ap_const_lv32_1B = "11011";
const sc_lv<32> base_add::ap_const_lv32_B = "1011";
const sc_lv<32> base_add::ap_const_lv32_3 = "11";

base_add::base_add(sc_module_name name) : sc_module(name), mVcdFile(0) {
    base_add_CTRL_s_axi_U = new base_add_CTRL_s_axi<C_S_AXI_CTRL_ADDR_WIDTH,C_S_AXI_CTRL_DATA_WIDTH>("base_add_CTRL_s_axi_U");
    base_add_CTRL_s_axi_U->AWVALID(s_axi_CTRL_AWVALID);
    base_add_CTRL_s_axi_U->AWREADY(s_axi_CTRL_AWREADY);
    base_add_CTRL_s_axi_U->AWADDR(s_axi_CTRL_AWADDR);
    base_add_CTRL_s_axi_U->WVALID(s_axi_CTRL_WVALID);
    base_add_CTRL_s_axi_U->WREADY(s_axi_CTRL_WREADY);
    base_add_CTRL_s_axi_U->WDATA(s_axi_CTRL_WDATA);
    base_add_CTRL_s_axi_U->WSTRB(s_axi_CTRL_WSTRB);
    base_add_CTRL_s_axi_U->ARVALID(s_axi_CTRL_ARVALID);
    base_add_CTRL_s_axi_U->ARREADY(s_axi_CTRL_ARREADY);
    base_add_CTRL_s_axi_U->ARADDR(s_axi_CTRL_ARADDR);
    base_add_CTRL_s_axi_U->RVALID(s_axi_CTRL_RVALID);
    base_add_CTRL_s_axi_U->RREADY(s_axi_CTRL_RREADY);
    base_add_CTRL_s_axi_U->RDATA(s_axi_CTRL_RDATA);
    base_add_CTRL_s_axi_U->RRESP(s_axi_CTRL_RRESP);
    base_add_CTRL_s_axi_U->BVALID(s_axi_CTRL_BVALID);
    base_add_CTRL_s_axi_U->BREADY(s_axi_CTRL_BREADY);
    base_add_CTRL_s_axi_U->BRESP(s_axi_CTRL_BRESP);
    base_add_CTRL_s_axi_U->ACLK(ap_clk);
    base_add_CTRL_s_axi_U->ARESET(ap_rst_n_inv);
    base_add_CTRL_s_axi_U->ACLK_EN(ap_var_for_const0);
    base_add_CTRL_s_axi_U->ap_start(ap_start);
    base_add_CTRL_s_axi_U->interrupt(interrupt);
    base_add_CTRL_s_axi_U->ap_ready(ap_ready);
    base_add_CTRL_s_axi_U->ap_done(ap_done);
    base_add_CTRL_s_axi_U->ap_idle(ap_idle);
    base_add_CTRL_s_axi_U->buffer_r(buffer_r);
    base_add_CTRL_s_axi_U->sample_count(sample_count);
    base_add_CTRL_s_axi_U->capture_mode(capture_mode);
    base_add_GMEM_m_axi_U = new base_add_GMEM_m_axi<0,32,32,5,16,16,16,16,C_M_AXI_GMEM_ID_WIDTH,C_M_AXI_GMEM_ADDR_WIDTH,C_M_AXI_GMEM_DATA_WIDTH,C_M_AXI_GMEM_AWUSER_WIDTH,C_M_AXI_GMEM_ARUSER_WIDTH,C_M_AXI_GMEM_WUSER_WIDTH,C_M_AXI_GMEM_RUSER_WIDTH,C_M_AXI_GMEM_BUSER_WIDTH,C_M_AXI_GMEM_USER_VALUE,C_M_AXI_GMEM_PROT_VALUE,C_M_AXI_GMEM_CACHE_VALUE>("base_add_GMEM_m_axi_U");
    base_add_GMEM_m_axi_U->AWVALID(m_axi_GMEM_AWVALID);
    base_add_GMEM_m_axi_U->AWREADY(m_axi_GMEM_AWREADY);
    base_add_GMEM_m_axi_U->AWADDR(m_axi_GMEM_AWADDR);
    base_add_GMEM_m_axi_U->AWID(m_axi_GMEM_AWID);
    base_add_GMEM_m_axi_U->AWLEN(m_axi_GMEM_AWLEN);
    base_add_GMEM_m_axi_U->AWSIZE(m_axi_GMEM_AWSIZE);
    base_add_GMEM_m_axi_U->AWBURST(m_axi_GMEM_AWBURST);
    base_add_GMEM_m_axi_U->AWLOCK(m_axi_GMEM_AWLOCK);
    base_add_GMEM_m_axi_U->AWCACHE(m_axi_GMEM_AWCACHE);
    base_add_GMEM_m_axi_U->AWPROT(m_axi_GMEM_AWPROT);
    base_add_GMEM_m_axi_U->AWQOS(m_axi_GMEM_AWQOS);
    base_add_GMEM_m_axi_U->AWREGION(m_axi_GMEM_AWREGION);
    base_add_GMEM_m_axi_U->AWUSER(m_axi_GMEM_AWUSER);
    base_add_GMEM_m_axi_U->WVALID(m_axi_GMEM_WVALID);
    base_add_GMEM_m_axi_U->WREADY(m_axi_GMEM_WREADY);
    base_add_GMEM_m_axi_U->WDATA(m_axi_GMEM_WDATA);
    base_add_GMEM_m_axi_U->WSTRB(m_axi_GMEM_WSTRB);
    base_add_GMEM_m_axi_U->WLAST(m_axi_GMEM_WLAST);
    base_add_GMEM_m_axi_U->WID(m_axi_GMEM_WID);
    base_add_GMEM_m_axi_U->WUSER(m_axi_GMEM_WUSER);
    base_add_GMEM_m_axi_U->ARVALID(m_axi_GMEM_ARVALID);
    base_add_GMEM_m_axi_U->ARREADY(m_axi_GMEM_ARREADY);
    base_add_GMEM_m_axi_U->ARADDR(m_axi_GMEM_ARADDR);
    base_add_GMEM_m_axi_U->ARID(m_axi_GMEM_ARID);
    base_add_GMEM_m_axi_U->ARLEN(m_axi_GMEM_ARLEN);
    base_add_GMEM_m_axi_U->ARSIZE(m_axi_GMEM_ARSIZE);
    base_add_GMEM_m_axi_U->ARBURST(m_axi_GMEM_ARBURST);
    base_add_GMEM_m_axi_U->ARLOCK(m_axi_GMEM_ARLOCK);
    base_add_GMEM_m_axi_U->ARCACHE(m_axi_GMEM_ARCACHE);
    base_add_GMEM_m_axi_U->ARPROT(m_axi_GMEM_ARPROT);
    base_add_GMEM_m_axi_U->ARQOS(m_axi_GMEM_ARQOS);
    base_add_GMEM_m_axi_U->ARREGION(m_axi_GMEM_ARREGION);
    base_add_GMEM_m_axi_U->ARUSER(m_axi_GMEM_ARUSER);
    base_add_GMEM_m_axi_U->RVALID(m_axi_GMEM_RVALID);
    base_add_GMEM_m_axi_U->RREADY(m_axi_GMEM_RREADY);
    base_add_GMEM_m_axi_U->RDATA(m_axi_GMEM_RDATA);
    base_add_GMEM_m_axi_U->RLAST(m_axi_GMEM_RLAST);
    base_add_GMEM_m_axi_U->RID(m_axi_GMEM_RID);
    base_add_GMEM_m_axi_U->RUSER(m_axi_GMEM_RUSER);
    base_add_GMEM_m_axi_U->RRESP(m_axi_GMEM_RRESP);
    base_add_GMEM_m_axi_U->BVALID(m_axi_GMEM_BVALID);
    base_add_GMEM_m_axi_U->BREADY(m_axi_GMEM_BREADY);
    base_add_GMEM_m_axi_U->BRESP(m_axi_GMEM_BRESP);
    base_add_GMEM_m_axi_U->BID(m_axi_GMEM_BID);
    base_add_GMEM_m_axi_U->BUSER(m_axi_GMEM_BUSER);
    base_add_GMEM_m_axi_U->ACLK(ap_clk);
    base_add_GMEM_m_axi_U->ARESET(ap_rst_n_inv);
    base_add_GMEM_m_axi_U->ACLK_EN(ap_var_for_const0);
    base_add_GMEM_m_axi_U->I_ARVALID(ap_var_for_const1);
    base_add_GMEM_m_axi_U->I_ARREADY(GMEM_ARREADY);
    base_add_GMEM_m_axi_U->I_ARADDR(ap_var_for_const2);
    base_add_GMEM_m_axi_U->I_ARID(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_ARLEN(ap_var_for_const2);
    base_add_GMEM_m_axi_U->I_ARSIZE(ap_var_for_const4);
    base_add_GMEM_m_axi_U->I_ARLOCK(ap_var_for_const5);
    base_add_GMEM_m_axi_U->I_ARCACHE(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_ARQOS(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_ARPROT(ap_var_for_const4);
    base_add_GMEM_m_axi_U->I_ARUSER(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_ARBURST(ap_var_for_const5);
    base_add_GMEM_m_axi_U->I_ARREGION(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_RVALID(GMEM_RVALID);
    base_add_GMEM_m_axi_U->I_RREADY(ap_var_for_const1);
    base_add_GMEM_m_axi_U->I_RDATA(GMEM_RDATA);
    base_add_GMEM_m_axi_U->I_RID(GMEM_RID);
    base_add_GMEM_m_axi_U->I_RUSER(GMEM_RUSER);
    base_add_GMEM_m_axi_U->I_RRESP(GMEM_RRESP);
    base_add_GMEM_m_axi_U->I_RLAST(GMEM_RLAST);
    base_add_GMEM_m_axi_U->I_AWVALID(GMEM_AWVALID);
    base_add_GMEM_m_axi_U->I_AWREADY(GMEM_AWREADY);
    base_add_GMEM_m_axi_U->I_AWADDR(GMEM_AWADDR);
    base_add_GMEM_m_axi_U->I_AWID(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_AWLEN(ap_var_for_const7);
    base_add_GMEM_m_axi_U->I_AWSIZE(ap_var_for_const4);
    base_add_GMEM_m_axi_U->I_AWLOCK(ap_var_for_const5);
    base_add_GMEM_m_axi_U->I_AWCACHE(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_AWQOS(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_AWPROT(ap_var_for_const4);
    base_add_GMEM_m_axi_U->I_AWUSER(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_AWBURST(ap_var_for_const5);
    base_add_GMEM_m_axi_U->I_AWREGION(ap_var_for_const6);
    base_add_GMEM_m_axi_U->I_WVALID(GMEM_WVALID);
    base_add_GMEM_m_axi_U->I_WREADY(GMEM_WREADY);
    base_add_GMEM_m_axi_U->I_WDATA(GMEM_WDATA);
    base_add_GMEM_m_axi_U->I_WID(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_WUSER(ap_var_for_const3);
    base_add_GMEM_m_axi_U->I_WLAST(ap_var_for_const1);
    base_add_GMEM_m_axi_U->I_WSTRB(ap_var_for_const8);
    base_add_GMEM_m_axi_U->I_BVALID(GMEM_BVALID);
    base_add_GMEM_m_axi_U->I_BREADY(GMEM_BREADY);
    base_add_GMEM_m_axi_U->I_BRESP(GMEM_BRESP);
    base_add_GMEM_m_axi_U->I_BID(GMEM_BID);
    base_add_GMEM_m_axi_U->I_BUSER(GMEM_BUSER);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_GMEM_AWADDR);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( buffer2_sum_cast_fu_327_p1 );
    sensitive << ( buffer2_sum3_cast_fu_357_p1 );
    sensitive << ( ap_reg_ioackin_GMEM_AWREADY );
    sensitive << ( ap_condition_658 );
    sensitive << ( ap_condition_662 );

    SC_METHOD(thread_GMEM_AWVALID);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( exitcond_reg_387 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_reg_ioackin_GMEM_AWREADY );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_GMEM_BREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_GMEM_WDATA);
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_reg_ioackin_GMEM_WREADY );
    sensitive << ( ch_cast_fu_352_p1 );
    sensitive << ( ch2_cast_fu_367_p1 );
    sensitive << ( ap_condition_469 );
    sensitive << ( ap_condition_486 );

    SC_METHOD(thread_GMEM_WVALID);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( ap_reg_ioackin_GMEM_WREADY );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_GMEM_blk_n_AW);
    sensitive << ( m_axi_GMEM_AWREADY );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_reg_387 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );

    SC_METHOD(thread_GMEM_blk_n_B);
    sensitive << ( m_axi_GMEM_BVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );

    SC_METHOD(thread_GMEM_blk_n_W);
    sensitive << ( m_axi_GMEM_WREADY );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( sample_stream_V_V_0_vld_out );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( GMEM_BVALID );
    sensitive << ( ap_predicate_op50_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( sample_stream_V_V_0_vld_out );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( GMEM_BVALID );
    sensitive << ( ap_predicate_op50_read_state4 );
    sensitive << ( ap_block_state4_io );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( sample_stream_V_V_0_vld_out );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( GMEM_BVALID );
    sensitive << ( ap_predicate_op50_read_state4 );
    sensitive << ( ap_block_state4_io );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_01001);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );
    sensitive << ( GMEM_BVALID );

    SC_METHOD(thread_ap_block_pp0_stage1_11001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );
    sensitive << ( GMEM_BVALID );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );
    sensitive << ( GMEM_BVALID );
    sensitive << ( ap_block_state5_io );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter4);
    sensitive << ( exitcond_reg_387_pp0_iter3_reg );
    sensitive << ( GMEM_BVALID );

    SC_METHOD(thread_ap_block_state11_pp0_stage1_iter4);
    sensitive << ( exitcond_reg_387_pp0_iter4_reg );
    sensitive << ( GMEM_BVALID );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( exitcond_reg_387 );
    sensitive << ( ap_sig_ioackin_GMEM_AWREADY );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( sample_stream_V_V_0_vld_out );
    sensitive << ( ap_predicate_op50_read_state4 );

    SC_METHOD(thread_ap_block_state5_io);
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_sig_ioackin_GMEM_AWREADY );
    sensitive << ( ap_sig_ioackin_GMEM_WREADY );

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_io);
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_sig_ioackin_GMEM_WREADY );

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage1_iter3);

    SC_METHOD(thread_ap_condition_469);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_ap_condition_486);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_ap_condition_658);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_reg_387 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_ap_condition_662);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( exitcond_reg_387_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage1_01001 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_fu_245_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_162_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_reg_387 );
    sensitive << ( i_reg_158 );
    sensitive << ( i_1_reg_391 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_ch2_reg_179);

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_ch_reg_170);

    SC_METHOD(thread_ap_predicate_op50_read_state4);
    sensitive << ( exitcond_reg_387 );
    sensitive << ( tmp_2_reg_383 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_GMEM_AWREADY);
    sensitive << ( GMEM_AWREADY );
    sensitive << ( ap_reg_ioackin_GMEM_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_GMEM_WREADY);
    sensitive << ( GMEM_WREADY );
    sensitive << ( ap_reg_ioackin_GMEM_WREADY );

    SC_METHOD(thread_buffer2_sum3_cast_fu_357_p1);
    sensitive << ( buffer2_sum3_reg_427 );

    SC_METHOD(thread_buffer2_sum3_fu_347_p2);
    sensitive << ( tmp_3_cast_reg_372 );
    sensitive << ( tmp_7_cast_fu_343_p1 );

    SC_METHOD(thread_buffer2_sum_cast_fu_327_p1);
    sensitive << ( buffer2_sum_reg_396 );

    SC_METHOD(thread_buffer2_sum_fu_260_p2);
    sensitive << ( tmp_3_cast_reg_372 );
    sensitive << ( tmp_cast_fu_256_p1 );

    SC_METHOD(thread_ch2_cast_fu_367_p1);
    sensitive << ( ch2_reg_179 );

    SC_METHOD(thread_ch_cast_fu_352_p1);
    sensitive << ( ap_phi_reg_pp0_iter1_ch_reg_170 );

    SC_METHOD(thread_exitcond_fu_245_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( n_1_reg_378 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i_phi_fu_162_p4 );

    SC_METHOD(thread_i_1_fu_250_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_162_p4 );

    SC_METHOD(thread_n_1_fu_231_p3);
    sensitive << ( tmp_1_fu_225_p2 );
    sensitive << ( tmp_7_fu_221_p1 );

    SC_METHOD(thread_p_lshr_f_fu_313_p4);
    sensitive << ( tri_3_fu_291_p3 );

    SC_METHOD(thread_p_sample_count_fu_213_p3);
    sensitive << ( tmp_fu_203_p2 );
    sensitive << ( tmp_4_fu_209_p1 );

    SC_METHOD(thread_phase_fu_265_p1);
    sensitive << ( i_reg_158 );

    SC_METHOD(thread_sample_stream_V_V_0_ack_in);
    sensitive << ( sample_stream_V_V_0_state );

    SC_METHOD(thread_sample_stream_V_V_0_ack_out);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_predicate_op50_read_state4 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_sample_stream_V_V_0_data_out);
    sensitive << ( sample_stream_V_V_0_payload_A );
    sensitive << ( sample_stream_V_V_0_payload_B );
    sensitive << ( sample_stream_V_V_0_sel );

    SC_METHOD(thread_sample_stream_V_V_0_load_A);
    sensitive << ( sample_stream_V_V_0_sel_wr );
    sensitive << ( sample_stream_V_V_0_state_cmp_full );

    SC_METHOD(thread_sample_stream_V_V_0_load_B);
    sensitive << ( sample_stream_V_V_0_sel_wr );
    sensitive << ( sample_stream_V_V_0_state_cmp_full );

    SC_METHOD(thread_sample_stream_V_V_0_sel);
    sensitive << ( sample_stream_V_V_0_sel_rd );

    SC_METHOD(thread_sample_stream_V_V_0_state_cmp_full);
    sensitive << ( sample_stream_V_V_0_state );

    SC_METHOD(thread_sample_stream_V_V_0_vld_in);
    sensitive << ( sample_stream_V_V_TVALID );

    SC_METHOD(thread_sample_stream_V_V_0_vld_out);
    sensitive << ( sample_stream_V_V_0_state );

    SC_METHOD(thread_sample_stream_V_V_TDATA_blk_n);
    sensitive << ( sample_stream_V_V_0_state );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_reg_387 );
    sensitive << ( tmp_2_reg_383 );

    SC_METHOD(thread_sample_stream_V_V_TREADY);
    sensitive << ( sample_stream_V_V_0_state );

    SC_METHOD(thread_tmp_10_fu_269_p3);
    sensitive << ( i_reg_158 );

    SC_METHOD(thread_tmp_11_fu_299_p1);
    sensitive << ( sample_stream_V_V_0_data_out );

    SC_METHOD(thread_tmp_1_fu_225_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_sample_count_fu_213_p3 );

    SC_METHOD(thread_tmp_2_fu_239_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( capture_mode );

    SC_METHOD(thread_tmp_3_cast_fu_199_p1);
    sensitive << ( tmp_3_fu_189_p4 );

    SC_METHOD(thread_tmp_3_fu_189_p4);
    sensitive << ( buffer_r );

    SC_METHOD(thread_tmp_4_fu_209_p1);
    sensitive << ( sample_count );

    SC_METHOD(thread_tmp_5_fu_337_p2);
    sensitive << ( i_reg_158 );

    SC_METHOD(thread_tmp_7_cast_fu_343_p1);
    sensitive << ( tmp_5_fu_337_p2 );

    SC_METHOD(thread_tmp_7_fu_221_p1);
    sensitive << ( p_sample_count_fu_213_p3 );

    SC_METHOD(thread_tmp_9_fu_323_p1);
    sensitive << ( p_lshr_f_fu_313_p4 );

    SC_METHOD(thread_tmp_cast_fu_256_p1);
    sensitive << ( i_reg_158 );

    SC_METHOD(thread_tmp_fu_203_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( sample_count );

    SC_METHOD(thread_tri_1_fu_285_p2);
    sensitive << ( tri_fu_277_p3 );

    SC_METHOD(thread_tri_3_fu_291_p3);
    sensitive << ( tri_fu_277_p3 );
    sensitive << ( tmp_10_fu_269_p3 );
    sensitive << ( tri_1_fu_285_p2 );

    SC_METHOD(thread_tri_fu_277_p3);
    sensitive << ( phase_fu_265_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_fu_245_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const8);

    ap_CS_fsm = "0001";
    sample_stream_V_V_0_sel_rd = SC_LOGIC_0;
    sample_stream_V_V_0_sel_wr = SC_LOGIC_0;
    sample_stream_V_V_0_state = "00";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_reg_ioackin_GMEM_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_GMEM_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "base_add_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, m_axi_GMEM_AWVALID, "(port)m_axi_GMEM_AWVALID");
    sc_trace(mVcdFile, m_axi_GMEM_AWREADY, "(port)m_axi_GMEM_AWREADY");
    sc_trace(mVcdFile, m_axi_GMEM_AWADDR, "(port)m_axi_GMEM_AWADDR");
    sc_trace(mVcdFile, m_axi_GMEM_AWID, "(port)m_axi_GMEM_AWID");
    sc_trace(mVcdFile, m_axi_GMEM_AWLEN, "(port)m_axi_GMEM_AWLEN");
    sc_trace(mVcdFile, m_axi_GMEM_AWSIZE, "(port)m_axi_GMEM_AWSIZE");
    sc_trace(mVcdFile, m_axi_GMEM_AWBURST, "(port)m_axi_GMEM_AWBURST");
    sc_trace(mVcdFile, m_axi_GMEM_AWLOCK, "(port)m_axi_GMEM_AWLOCK");
    sc_trace(mVcdFile, m_axi_GMEM_AWCACHE, "(port)m_axi_GMEM_AWCACHE");
    sc_trace(mVcdFile, m_axi_GMEM_AWPROT, "(port)m_axi_GMEM_AWPROT");
    sc_trace(mVcdFile, m_axi_GMEM_AWQOS, "(port)m_axi_GMEM_AWQOS");
    sc_trace(mVcdFile, m_axi_GMEM_AWREGION, "(port)m_axi_GMEM_AWREGION");
    sc_trace(mVcdFile, m_axi_GMEM_AWUSER, "(port)m_axi_GMEM_AWUSER");
    sc_trace(mVcdFile, m_axi_GMEM_WVALID, "(port)m_axi_GMEM_WVALID");
    sc_trace(mVcdFile, m_axi_GMEM_WREADY, "(port)m_axi_GMEM_WREADY");
    sc_trace(mVcdFile, m_axi_GMEM_WDATA, "(port)m_axi_GMEM_WDATA");
    sc_trace(mVcdFile, m_axi_GMEM_WSTRB, "(port)m_axi_GMEM_WSTRB");
    sc_trace(mVcdFile, m_axi_GMEM_WLAST, "(port)m_axi_GMEM_WLAST");
    sc_trace(mVcdFile, m_axi_GMEM_WID, "(port)m_axi_GMEM_WID");
    sc_trace(mVcdFile, m_axi_GMEM_WUSER, "(port)m_axi_GMEM_WUSER");
    sc_trace(mVcdFile, m_axi_GMEM_ARVALID, "(port)m_axi_GMEM_ARVALID");
    sc_trace(mVcdFile, m_axi_GMEM_ARREADY, "(port)m_axi_GMEM_ARREADY");
    sc_trace(mVcdFile, m_axi_GMEM_ARADDR, "(port)m_axi_GMEM_ARADDR");
    sc_trace(mVcdFile, m_axi_GMEM_ARID, "(port)m_axi_GMEM_ARID");
    sc_trace(mVcdFile, m_axi_GMEM_ARLEN, "(port)m_axi_GMEM_ARLEN");
    sc_trace(mVcdFile, m_axi_GMEM_ARSIZE, "(port)m_axi_GMEM_ARSIZE");
    sc_trace(mVcdFile, m_axi_GMEM_ARBURST, "(port)m_axi_GMEM_ARBURST");
    sc_trace(mVcdFile, m_axi_GMEM_ARLOCK, "(port)m_axi_GMEM_ARLOCK");
    sc_trace(mVcdFile, m_axi_GMEM_ARCACHE, "(port)m_axi_GMEM_ARCACHE");
    sc_trace(mVcdFile, m_axi_GMEM_ARPROT, "(port)m_axi_GMEM_ARPROT");
    sc_trace(mVcdFile, m_axi_GMEM_ARQOS, "(port)m_axi_GMEM_ARQOS");
    sc_trace(mVcdFile, m_axi_GMEM_ARREGION, "(port)m_axi_GMEM_ARREGION");
    sc_trace(mVcdFile, m_axi_GMEM_ARUSER, "(port)m_axi_GMEM_ARUSER");
    sc_trace(mVcdFile, m_axi_GMEM_RVALID, "(port)m_axi_GMEM_RVALID");
    sc_trace(mVcdFile, m_axi_GMEM_RREADY, "(port)m_axi_GMEM_RREADY");
    sc_trace(mVcdFile, m_axi_GMEM_RDATA, "(port)m_axi_GMEM_RDATA");
    sc_trace(mVcdFile, m_axi_GMEM_RLAST, "(port)m_axi_GMEM_RLAST");
    sc_trace(mVcdFile, m_axi_GMEM_RID, "(port)m_axi_GMEM_RID");
    sc_trace(mVcdFile, m_axi_GMEM_RUSER, "(port)m_axi_GMEM_RUSER");
    sc_trace(mVcdFile, m_axi_GMEM_RRESP, "(port)m_axi_GMEM_RRESP");
    sc_trace(mVcdFile, m_axi_GMEM_BVALID, "(port)m_axi_GMEM_BVALID");
    sc_trace(mVcdFile, m_axi_GMEM_BREADY, "(port)m_axi_GMEM_BREADY");
    sc_trace(mVcdFile, m_axi_GMEM_BRESP, "(port)m_axi_GMEM_BRESP");
    sc_trace(mVcdFile, m_axi_GMEM_BID, "(port)m_axi_GMEM_BID");
    sc_trace(mVcdFile, m_axi_GMEM_BUSER, "(port)m_axi_GMEM_BUSER");
    sc_trace(mVcdFile, sample_stream_V_V_TDATA, "(port)sample_stream_V_V_TDATA");
    sc_trace(mVcdFile, sample_stream_V_V_TVALID, "(port)sample_stream_V_V_TVALID");
    sc_trace(mVcdFile, sample_stream_V_V_TREADY, "(port)sample_stream_V_V_TREADY");
    sc_trace(mVcdFile, s_axi_CTRL_AWVALID, "(port)s_axi_CTRL_AWVALID");
    sc_trace(mVcdFile, s_axi_CTRL_AWREADY, "(port)s_axi_CTRL_AWREADY");
    sc_trace(mVcdFile, s_axi_CTRL_AWADDR, "(port)s_axi_CTRL_AWADDR");
    sc_trace(mVcdFile, s_axi_CTRL_WVALID, "(port)s_axi_CTRL_WVALID");
    sc_trace(mVcdFile, s_axi_CTRL_WREADY, "(port)s_axi_CTRL_WREADY");
    sc_trace(mVcdFile, s_axi_CTRL_WDATA, "(port)s_axi_CTRL_WDATA");
    sc_trace(mVcdFile, s_axi_CTRL_WSTRB, "(port)s_axi_CTRL_WSTRB");
    sc_trace(mVcdFile, s_axi_CTRL_ARVALID, "(port)s_axi_CTRL_ARVALID");
    sc_trace(mVcdFile, s_axi_CTRL_ARREADY, "(port)s_axi_CTRL_ARREADY");
    sc_trace(mVcdFile, s_axi_CTRL_ARADDR, "(port)s_axi_CTRL_ARADDR");
    sc_trace(mVcdFile, s_axi_CTRL_RVALID, "(port)s_axi_CTRL_RVALID");
    sc_trace(mVcdFile, s_axi_CTRL_RREADY, "(port)s_axi_CTRL_RREADY");
    sc_trace(mVcdFile, s_axi_CTRL_RDATA, "(port)s_axi_CTRL_RDATA");
    sc_trace(mVcdFile, s_axi_CTRL_RRESP, "(port)s_axi_CTRL_RRESP");
    sc_trace(mVcdFile, s_axi_CTRL_BVALID, "(port)s_axi_CTRL_BVALID");
    sc_trace(mVcdFile, s_axi_CTRL_BREADY, "(port)s_axi_CTRL_BREADY");
    sc_trace(mVcdFile, s_axi_CTRL_BRESP, "(port)s_axi_CTRL_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, buffer_r, "buffer_r");
    sc_trace(mVcdFile, sample_count, "sample_count");
    sc_trace(mVcdFile, capture_mode, "capture_mode");
    sc_trace(mVcdFile, sample_stream_V_V_0_data_out, "sample_stream_V_V_0_data_out");
    sc_trace(mVcdFile, sample_stream_V_V_0_vld_in, "sample_stream_V_V_0_vld_in");
    sc_trace(mVcdFile, sample_stream_V_V_0_vld_out, "sample_stream_V_V_0_vld_out");
    sc_trace(mVcdFile, sample_stream_V_V_0_ack_in, "sample_stream_V_V_0_ack_in");
    sc_trace(mVcdFile, sample_stream_V_V_0_ack_out, "sample_stream_V_V_0_ack_out");
    sc_trace(mVcdFile, sample_stream_V_V_0_payload_A, "sample_stream_V_V_0_payload_A");
    sc_trace(mVcdFile, sample_stream_V_V_0_payload_B, "sample_stream_V_V_0_payload_B");
    sc_trace(mVcdFile, sample_stream_V_V_0_sel_rd, "sample_stream_V_V_0_sel_rd");
    sc_trace(mVcdFile, sample_stream_V_V_0_sel_wr, "sample_stream_V_V_0_sel_wr");
    sc_trace(mVcdFile, sample_stream_V_V_0_sel, "sample_stream_V_V_0_sel");
    sc_trace(mVcdFile, sample_stream_V_V_0_load_A, "sample_stream_V_V_0_load_A");
    sc_trace(mVcdFile, sample_stream_V_V_0_load_B, "sample_stream_V_V_0_load_B");
    sc_trace(mVcdFile, sample_stream_V_V_0_state, "sample_stream_V_V_0_state");
    sc_trace(mVcdFile, sample_stream_V_V_0_state_cmp_full, "sample_stream_V_V_0_state_cmp_full");
    sc_trace(mVcdFile, GMEM_blk_n_AW, "GMEM_blk_n_AW");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_reg_387, "exitcond_reg_387");
    sc_trace(mVcdFile, GMEM_blk_n_W, "GMEM_blk_n_W");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, exitcond_reg_387_pp0_iter1_reg, "exitcond_reg_387_pp0_iter1_reg");
    sc_trace(mVcdFile, GMEM_blk_n_B, "GMEM_blk_n_B");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, exitcond_reg_387_pp0_iter3_reg, "exitcond_reg_387_pp0_iter3_reg");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, exitcond_reg_387_pp0_iter4_reg, "exitcond_reg_387_pp0_iter4_reg");
    sc_trace(mVcdFile, sample_stream_V_V_TDATA_blk_n, "sample_stream_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, tmp_2_reg_383, "tmp_2_reg_383");
    sc_trace(mVcdFile, GMEM_AWVALID, "GMEM_AWVALID");
    sc_trace(mVcdFile, GMEM_AWREADY, "GMEM_AWREADY");
    sc_trace(mVcdFile, GMEM_AWADDR, "GMEM_AWADDR");
    sc_trace(mVcdFile, GMEM_WVALID, "GMEM_WVALID");
    sc_trace(mVcdFile, GMEM_WREADY, "GMEM_WREADY");
    sc_trace(mVcdFile, GMEM_WDATA, "GMEM_WDATA");
    sc_trace(mVcdFile, GMEM_ARREADY, "GMEM_ARREADY");
    sc_trace(mVcdFile, GMEM_RVALID, "GMEM_RVALID");
    sc_trace(mVcdFile, GMEM_RDATA, "GMEM_RDATA");
    sc_trace(mVcdFile, GMEM_RLAST, "GMEM_RLAST");
    sc_trace(mVcdFile, GMEM_RID, "GMEM_RID");
    sc_trace(mVcdFile, GMEM_RUSER, "GMEM_RUSER");
    sc_trace(mVcdFile, GMEM_RRESP, "GMEM_RRESP");
    sc_trace(mVcdFile, GMEM_BVALID, "GMEM_BVALID");
    sc_trace(mVcdFile, GMEM_BREADY, "GMEM_BREADY");
    sc_trace(mVcdFile, GMEM_BRESP, "GMEM_BRESP");
    sc_trace(mVcdFile, GMEM_BID, "GMEM_BID");
    sc_trace(mVcdFile, GMEM_BUSER, "GMEM_BUSER");
    sc_trace(mVcdFile, i_reg_158, "i_reg_158");
    sc_trace(mVcdFile, ch2_reg_179, "ch2_reg_179");
    sc_trace(mVcdFile, tmp_3_cast_fu_199_p1, "tmp_3_cast_fu_199_p1");
    sc_trace(mVcdFile, tmp_3_cast_reg_372, "tmp_3_cast_reg_372");
    sc_trace(mVcdFile, n_1_fu_231_p3, "n_1_fu_231_p3");
    sc_trace(mVcdFile, n_1_reg_378, "n_1_reg_378");
    sc_trace(mVcdFile, tmp_2_fu_239_p2, "tmp_2_fu_239_p2");
    sc_trace(mVcdFile, exitcond_fu_245_p2, "exitcond_fu_245_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_predicate_op50_read_state4, "ap_predicate_op50_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_sig_ioackin_GMEM_AWREADY, "ap_sig_ioackin_GMEM_AWREADY");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_sig_ioackin_GMEM_WREADY, "ap_sig_ioackin_GMEM_WREADY");
    sc_trace(mVcdFile, ap_block_state6_io, "ap_block_state6_io");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter4, "ap_block_state10_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_reg_387_pp0_iter2_reg, "exitcond_reg_387_pp0_iter2_reg");
    sc_trace(mVcdFile, i_1_fu_250_p2, "i_1_fu_250_p2");
    sc_trace(mVcdFile, i_1_reg_391, "i_1_reg_391");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, buffer2_sum_fu_260_p2, "buffer2_sum_fu_260_p2");
    sc_trace(mVcdFile, buffer2_sum_reg_396, "buffer2_sum_reg_396");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state5_io, "ap_block_state5_io");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter2, "ap_block_state7_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage1_iter3, "ap_block_state9_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage1_iter4, "ap_block_state11_pp0_stage1_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, tri_3_fu_291_p3, "tri_3_fu_291_p3");
    sc_trace(mVcdFile, tmp_11_fu_299_p1, "tmp_11_fu_299_p1");
    sc_trace(mVcdFile, tmp_9_fu_323_p1, "tmp_9_fu_323_p1");
    sc_trace(mVcdFile, buffer2_sum3_fu_347_p2, "buffer2_sum3_fu_347_p2");
    sc_trace(mVcdFile, buffer2_sum3_reg_427, "buffer2_sum3_reg_427");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_162_p4, "ap_phi_mux_i_phi_fu_162_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_ch_reg_170, "ap_phi_reg_pp0_iter0_ch_reg_170");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_ch_reg_170, "ap_phi_reg_pp0_iter1_ch_reg_170");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_ch2_reg_179, "ap_phi_reg_pp0_iter0_ch2_reg_179");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_ch2_reg_179, "ap_phi_reg_pp0_iter1_ch2_reg_179");
    sc_trace(mVcdFile, buffer2_sum_cast_fu_327_p1, "buffer2_sum_cast_fu_327_p1");
    sc_trace(mVcdFile, buffer2_sum3_cast_fu_357_p1, "buffer2_sum3_cast_fu_357_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_GMEM_AWREADY, "ap_reg_ioackin_GMEM_AWREADY");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, ap_reg_ioackin_GMEM_WREADY, "ap_reg_ioackin_GMEM_WREADY");
    sc_trace(mVcdFile, ap_block_pp0_stage1_01001, "ap_block_pp0_stage1_01001");
    sc_trace(mVcdFile, ch_cast_fu_352_p1, "ch_cast_fu_352_p1");
    sc_trace(mVcdFile, ch2_cast_fu_367_p1, "ch2_cast_fu_367_p1");
    sc_trace(mVcdFile, tmp_3_fu_189_p4, "tmp_3_fu_189_p4");
    sc_trace(mVcdFile, tmp_fu_203_p2, "tmp_fu_203_p2");
    sc_trace(mVcdFile, tmp_4_fu_209_p1, "tmp_4_fu_209_p1");
    sc_trace(mVcdFile, p_sample_count_fu_213_p3, "p_sample_count_fu_213_p3");
    sc_trace(mVcdFile, tmp_1_fu_225_p2, "tmp_1_fu_225_p2");
    sc_trace(mVcdFile, tmp_7_fu_221_p1, "tmp_7_fu_221_p1");
    sc_trace(mVcdFile, tmp_cast_fu_256_p1, "tmp_cast_fu_256_p1");
    sc_trace(mVcdFile, phase_fu_265_p1, "phase_fu_265_p1");
    sc_trace(mVcdFile, tri_fu_277_p3, "tri_fu_277_p3");
    sc_trace(mVcdFile, tmp_10_fu_269_p3, "tmp_10_fu_269_p3");
    sc_trace(mVcdFile, tri_1_fu_285_p2, "tri_1_fu_285_p2");
    sc_trace(mVcdFile, p_lshr_f_fu_313_p4, "p_lshr_f_fu_313_p4");
    sc_trace(mVcdFile, tmp_5_fu_337_p2, "tmp_5_fu_337_p2");
    sc_trace(mVcdFile, tmp_7_cast_fu_343_p1, "tmp_7_cast_fu_343_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_658, "ap_condition_658");
    sc_trace(mVcdFile, ap_condition_662, "ap_condition_662");
    sc_trace(mVcdFile, ap_condition_469, "ap_condition_469");
    sc_trace(mVcdFile, ap_condition_486, "ap_condition_486");
#endif

    }
    mHdltvinHandle.open("base_add.hdltvin.dat");
    mHdltvoutHandle.open("base_add.hdltvout.dat");
}

base_add::~base_add() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete base_add_CTRL_s_axi_U;
    delete base_add_GMEM_m_axi_U;
}

void base_add::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void base_add::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_0;
}

void base_add::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_0;
}

void base_add::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv1_0;
}

void base_add::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv2_0;
}

void base_add::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv32_1;
}

void base_add::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv3_0;
}

void base_add::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_lv4_0;
}

void base_add::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv4_F;
}

void base_add::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()))) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_383.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter1_ch2_reg_179 = sample_stream_V_V_0_data_out.read().range(27, 16);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_reg_383.read()))) {
        ap_phi_reg_pp0_iter1_ch2_reg_179 = tmp_9_fu_323_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter1_ch2_reg_179 = ap_phi_reg_pp0_iter0_ch2_reg_179.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_383.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter1_ch_reg_170 = tmp_11_fu_299_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, tmp_2_reg_383.read()))) {
        ap_phi_reg_pp0_iter1_ch_reg_170 = tri_3_fu_291_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter1_ch_reg_170 = ap_phi_reg_pp0_iter0_ch_reg_170.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
            ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, GMEM_AWREADY.read()) && 
                     esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, GMEM_AWREADY.read()) && 
                     esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0)))) {
            ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
            ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, GMEM_WREADY.read()) && 
                     esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                     esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, GMEM_WREADY.read())))) {
            ap_reg_ioackin_GMEM_WREADY = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_reg_158 = i_1_reg_391.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_158 = ap_const_lv17_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        sample_stream_V_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_vld_out.read()))) {
            sample_stream_V_V_0_sel_rd =  (sc_logic) (~sample_stream_V_V_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        sample_stream_V_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_ack_in.read()))) {
            sample_stream_V_V_0_sel_wr =  (sc_logic) (~sample_stream_V_V_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        sample_stream_V_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_2)))) {
            sample_stream_V_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_1)))) {
            sample_stream_V_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(sample_stream_V_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_ack_out.read()))))) {
            sample_stream_V_V_0_state = ap_const_lv2_3;
        } else {
            sample_stream_V_V_0_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        buffer2_sum3_reg_427 = buffer2_sum3_fu_347_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        buffer2_sum_reg_396 = buffer2_sum_fu_260_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        ch2_reg_179 = ap_phi_reg_pp0_iter1_ch2_reg_179.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_387 = exitcond_fu_245_p2.read();
        exitcond_reg_387_pp0_iter1_reg = exitcond_reg_387.read();
        exitcond_reg_387_pp0_iter2_reg = exitcond_reg_387_pp0_iter1_reg.read();
        exitcond_reg_387_pp0_iter3_reg = exitcond_reg_387_pp0_iter2_reg.read();
        exitcond_reg_387_pp0_iter4_reg = exitcond_reg_387_pp0_iter3_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        i_1_reg_391 = i_1_fu_250_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n_1_reg_378 = n_1_fu_231_p3.read();
        tmp_2_reg_383 = tmp_2_fu_239_p2.read();
        tmp_3_cast_reg_372 = tmp_3_cast_fu_199_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_load_A.read())) {
        sample_stream_V_V_0_payload_A = sample_stream_V_V_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_load_B.read())) {
        sample_stream_V_V_0_payload_B = sample_stream_V_V_TDATA.read();
    }
}

void base_add::thread_GMEM_AWADDR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_AWREADY.read()))) {
        if (esl_seteq<1,1,1>(ap_condition_662.read(), ap_const_boolean_1)) {
            GMEM_AWADDR =  (sc_lv<32>) (buffer2_sum3_cast_fu_357_p1.read());
        } else if (esl_seteq<1,1,1>(ap_condition_658.read(), ap_const_boolean_1)) {
            GMEM_AWADDR =  (sc_lv<32>) (buffer2_sum_cast_fu_327_p1.read());
        } else {
            GMEM_AWADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        GMEM_AWADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void base_add::thread_GMEM_AWVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_AWREADY.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_AWREADY.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0)))) {
        GMEM_AWVALID = ap_const_logic_1;
    } else {
        GMEM_AWVALID = ap_const_logic_0;
    }
}

void base_add::thread_GMEM_BREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        GMEM_BREADY = ap_const_logic_1;
    } else {
        GMEM_BREADY = ap_const_logic_0;
    }
}

void base_add::thread_GMEM_WDATA() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_WREADY.read()))) {
        if (esl_seteq<1,1,1>(ap_condition_486.read(), ap_const_boolean_1)) {
            GMEM_WDATA = ch2_cast_fu_367_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_469.read(), ap_const_boolean_1)) {
            GMEM_WDATA = ch_cast_fu_352_p1.read();
        } else {
            GMEM_WDATA = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        GMEM_WDATA = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void base_add::thread_GMEM_WVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_WREADY.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_WREADY.read())))) {
        GMEM_WVALID = ap_const_logic_1;
    } else {
        GMEM_WVALID = ap_const_logic_0;
    }
}

void base_add::thread_GMEM_blk_n_AW() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read())))) {
        GMEM_blk_n_AW = m_axi_GMEM_AWREADY.read();
    } else {
        GMEM_blk_n_AW = ap_const_logic_1;
    }
}

void base_add::thread_GMEM_blk_n_B() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read())))) {
        GMEM_blk_n_B = m_axi_GMEM_BVALID.read();
    } else {
        GMEM_blk_n_B = ap_const_logic_1;
    }
}

void base_add::thread_GMEM_blk_n_W() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read())))) {
        GMEM_blk_n_W = m_axi_GMEM_WREADY.read();
    } else {
        GMEM_blk_n_W = ap_const_logic_1;
    }
}

void base_add::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void base_add::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void base_add::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void base_add::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[3];
}

void base_add::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op50_read_state4.read())));
}

void base_add::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_out.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op50_read_state4.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read())));
}

void base_add::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  ((esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_out.read()) && 
    esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op50_read_state4.read())) || 
   esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read()))) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read())));
}

void base_add::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_pp0_stage1_01001() {
    ap_block_pp0_stage1_01001 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read()));
}

void base_add::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read())));
}

void base_add::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state5_io.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read())));
}

void base_add::thread_ap_block_state10_pp0_stage0_iter4() {
    ap_block_state10_pp0_stage0_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read()));
}

void base_add::thread_ap_block_state11_pp0_stage1_iter4() {
    ap_block_state11_pp0_stage1_iter4 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, GMEM_BVALID.read()));
}

void base_add::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state4_io() {
    ap_block_state4_io = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_GMEM_AWREADY.read()));
}

void base_add::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_logic_0, sample_stream_V_V_0_vld_out.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op50_read_state4.read()));
}

void base_add::thread_ap_block_state5_io() {
    ap_block_state5_io = ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_GMEM_WREADY.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_GMEM_AWREADY.read())));
}

void base_add::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state6_io() {
    ap_block_state6_io = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_GMEM_WREADY.read()));
}

void base_add::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state7_pp0_stage1_iter2() {
    ap_block_state7_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_block_state9_pp0_stage1_iter3() {
    ap_block_state9_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void base_add::thread_ap_condition_469() {
    ap_condition_469 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0));
}

void base_add::thread_ap_condition_486() {
    ap_condition_486 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0));
}

void base_add::thread_ap_condition_658() {
    ap_condition_658 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_01001.read(), ap_const_boolean_0));
}

void base_add::thread_ap_condition_662() {
    ap_condition_662 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_01001.read(), ap_const_boolean_0));
}

void base_add::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_fu_245_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void base_add::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void base_add::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void base_add::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void base_add::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void base_add::thread_ap_phi_mux_i_phi_fu_162_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()))) {
        ap_phi_mux_i_phi_fu_162_p4 = i_1_reg_391.read();
    } else {
        ap_phi_mux_i_phi_fu_162_p4 = i_reg_158.read();
    }
}

void base_add::thread_ap_phi_reg_pp0_iter0_ch2_reg_179() {
    ap_phi_reg_pp0_iter0_ch2_reg_179 =  (sc_lv<12>) ("XXXXXXXXXXXX");
}

void base_add::thread_ap_phi_reg_pp0_iter0_ch_reg_170() {
    ap_phi_reg_pp0_iter0_ch_reg_170 =  (sc_lv<12>) ("XXXXXXXXXXXX");
}

void base_add::thread_ap_predicate_op50_read_state4() {
    ap_predicate_op50_read_state4 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_383.read()));
}

void base_add::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void base_add::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void base_add::thread_ap_sig_ioackin_GMEM_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_AWREADY.read())) {
        ap_sig_ioackin_GMEM_AWREADY = GMEM_AWREADY.read();
    } else {
        ap_sig_ioackin_GMEM_AWREADY = ap_const_logic_1;
    }
}

void base_add::thread_ap_sig_ioackin_GMEM_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_GMEM_WREADY.read())) {
        ap_sig_ioackin_GMEM_WREADY = GMEM_WREADY.read();
    } else {
        ap_sig_ioackin_GMEM_WREADY = ap_const_logic_1;
    }
}

void base_add::thread_buffer2_sum3_cast_fu_357_p1() {
    buffer2_sum3_cast_fu_357_p1 = esl_zext<64,31>(buffer2_sum3_reg_427.read());
}

void base_add::thread_buffer2_sum3_fu_347_p2() {
    buffer2_sum3_fu_347_p2 = (!tmp_7_cast_fu_343_p1.read().is_01() || !tmp_3_cast_reg_372.read().is_01())? sc_lv<31>(): (sc_biguint<31>(tmp_7_cast_fu_343_p1.read()) + sc_biguint<31>(tmp_3_cast_reg_372.read()));
}

void base_add::thread_buffer2_sum_cast_fu_327_p1() {
    buffer2_sum_cast_fu_327_p1 = esl_zext<64,31>(buffer2_sum_reg_396.read());
}

void base_add::thread_buffer2_sum_fu_260_p2() {
    buffer2_sum_fu_260_p2 = (!tmp_cast_fu_256_p1.read().is_01() || !tmp_3_cast_reg_372.read().is_01())? sc_lv<31>(): (sc_biguint<31>(tmp_cast_fu_256_p1.read()) + sc_biguint<31>(tmp_3_cast_reg_372.read()));
}

void base_add::thread_ch2_cast_fu_367_p1() {
    ch2_cast_fu_367_p1 = esl_zext<32,12>(ch2_reg_179.read());
}

void base_add::thread_ch_cast_fu_352_p1() {
    ch_cast_fu_352_p1 = esl_zext<32,12>(ap_phi_reg_pp0_iter1_ch_reg_170.read());
}

void base_add::thread_exitcond_fu_245_p2() {
    exitcond_fu_245_p2 = (!ap_phi_mux_i_phi_fu_162_p4.read().is_01() || !n_1_reg_378.read().is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_phi_fu_162_p4.read() == n_1_reg_378.read());
}

void base_add::thread_i_1_fu_250_p2() {
    i_1_fu_250_p2 = (!ap_phi_mux_i_phi_fu_162_p4.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_biguint<17>(ap_phi_mux_i_phi_fu_162_p4.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void base_add::thread_n_1_fu_231_p3() {
    n_1_fu_231_p3 = (!tmp_1_fu_225_p2.read()[0].is_01())? sc_lv<17>(): ((tmp_1_fu_225_p2.read()[0].to_bool())? ap_const_lv17_10000: tmp_7_fu_221_p1.read());
}

void base_add::thread_p_lshr_f_fu_313_p4() {
    p_lshr_f_fu_313_p4 = tri_3_fu_291_p3.read().range(11, 1);
}

void base_add::thread_p_sample_count_fu_213_p3() {
    p_sample_count_fu_213_p3 = (!tmp_fu_203_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_fu_203_p2.read()[0].to_bool())? ap_const_lv31_1: tmp_4_fu_209_p1.read());
}

void base_add::thread_phase_fu_265_p1() {
    phase_fu_265_p1 = i_reg_158.read().range(8-1, 0);
}

void base_add::thread_sample_stream_V_V_0_ack_in() {
    sample_stream_V_V_0_ack_in = sample_stream_V_V_0_state.read()[1];
}

void base_add::thread_sample_stream_V_V_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op50_read_state4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        sample_stream_V_V_0_ack_out = ap_const_logic_1;
    } else {
        sample_stream_V_V_0_ack_out = ap_const_logic_0;
    }
}

void base_add::thread_sample_stream_V_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, sample_stream_V_V_0_sel.read())) {
        sample_stream_V_V_0_data_out = sample_stream_V_V_0_payload_B.read();
    } else {
        sample_stream_V_V_0_data_out = sample_stream_V_V_0_payload_A.read();
    }
}

void base_add::thread_sample_stream_V_V_0_load_A() {
    sample_stream_V_V_0_load_A = (sample_stream_V_V_0_state_cmp_full.read() & ~sample_stream_V_V_0_sel_wr.read());
}

void base_add::thread_sample_stream_V_V_0_load_B() {
    sample_stream_V_V_0_load_B = (sample_stream_V_V_0_sel_wr.read() & sample_stream_V_V_0_state_cmp_full.read());
}

void base_add::thread_sample_stream_V_V_0_sel() {
    sample_stream_V_V_0_sel = sample_stream_V_V_0_sel_rd.read();
}

void base_add::thread_sample_stream_V_V_0_state_cmp_full() {
    sample_stream_V_V_0_state_cmp_full =  (sc_logic) ((!sample_stream_V_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(sample_stream_V_V_0_state.read() != ap_const_lv2_1))[0];
}

void base_add::thread_sample_stream_V_V_0_vld_in() {
    sample_stream_V_V_0_vld_in = sample_stream_V_V_TVALID.read();
}

void base_add::thread_sample_stream_V_V_0_vld_out() {
    sample_stream_V_V_0_vld_out = sample_stream_V_V_0_state.read()[0];
}

void base_add::thread_sample_stream_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_387.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_reg_383.read()))) {
        sample_stream_V_V_TDATA_blk_n = sample_stream_V_V_0_state.read()[0];
    } else {
        sample_stream_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void base_add::thread_sample_stream_V_V_TREADY() {
    sample_stream_V_V_TREADY = sample_stream_V_V_0_state.read()[1];
}

void base_add::thread_tmp_10_fu_269_p3() {
    tmp_10_fu_269_p3 = i_reg_158.read().range(7, 7);
}

void base_add::thread_tmp_11_fu_299_p1() {
    tmp_11_fu_299_p1 = sample_stream_V_V_0_data_out.read().range(12-1, 0);
}

void base_add::thread_tmp_1_fu_225_p2() {
    tmp_1_fu_225_p2 = (!p_sample_count_fu_213_p3.read().is_01() || !ap_const_lv31_10000.is_01())? sc_lv<1>(): (sc_biguint<31>(p_sample_count_fu_213_p3.read()) > sc_biguint<31>(ap_const_lv31_10000));
}

void base_add::thread_tmp_2_fu_239_p2() {
    tmp_2_fu_239_p2 = (!capture_mode.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(capture_mode.read() == ap_const_lv32_0);
}

void base_add::thread_tmp_3_cast_fu_199_p1() {
    tmp_3_cast_fu_199_p1 = esl_zext<31,30>(tmp_3_fu_189_p4.read());
}

void base_add::thread_tmp_3_fu_189_p4() {
    tmp_3_fu_189_p4 = buffer_r.read().range(31, 2);
}

void base_add::thread_tmp_4_fu_209_p1() {
    tmp_4_fu_209_p1 = sample_count.read().range(31-1, 0);
}

void base_add::thread_tmp_5_fu_337_p2() {
    tmp_5_fu_337_p2 = (i_reg_158.read() ^ ap_const_lv17_10000);
}

void base_add::thread_tmp_7_cast_fu_343_p1() {
    tmp_7_cast_fu_343_p1 = esl_zext<31,17>(tmp_5_fu_337_p2.read());
}

void base_add::thread_tmp_7_fu_221_p1() {
    tmp_7_fu_221_p1 = p_sample_count_fu_213_p3.read().range(17-1, 0);
}

void base_add::thread_tmp_9_fu_323_p1() {
    tmp_9_fu_323_p1 = esl_zext<12,11>(p_lshr_f_fu_313_p4.read());
}

void base_add::thread_tmp_cast_fu_256_p1() {
    tmp_cast_fu_256_p1 = esl_zext<31,17>(i_reg_158.read());
}

void base_add::thread_tmp_fu_203_p2() {
    tmp_fu_203_p2 = (!sample_count.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): (sc_bigint<32>(sample_count.read()) < sc_bigint<32>(ap_const_lv32_1));
}

void base_add::thread_tri_1_fu_285_p2() {
    tri_1_fu_285_p2 = (tri_fu_277_p3.read() ^ ap_const_lv12_FF0);
}

void base_add::thread_tri_3_fu_291_p3() {
    tri_3_fu_291_p3 = (!tmp_10_fu_269_p3.read()[0].is_01())? sc_lv<12>(): ((tmp_10_fu_269_p3.read()[0].to_bool())? tri_1_fu_285_p2.read(): tri_fu_277_p3.read());
}

void base_add::thread_tri_fu_277_p3() {
    tri_fu_277_p3 = esl_concat<8,4>(phase_fu_265_p1.read(), ap_const_lv4_0);
}

void base_add::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_fu_245_p2.read(), ap_const_lv1_1)) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_fu_245_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read())) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

void base_add::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"m_axi_GMEM_AWVALID\" :  \"" << m_axi_GMEM_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_AWREADY\" :  \"" << m_axi_GMEM_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWADDR\" :  \"" << m_axi_GMEM_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWID\" :  \"" << m_axi_GMEM_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWLEN\" :  \"" << m_axi_GMEM_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWSIZE\" :  \"" << m_axi_GMEM_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWBURST\" :  \"" << m_axi_GMEM_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWLOCK\" :  \"" << m_axi_GMEM_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWCACHE\" :  \"" << m_axi_GMEM_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWPROT\" :  \"" << m_axi_GMEM_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWQOS\" :  \"" << m_axi_GMEM_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWREGION\" :  \"" << m_axi_GMEM_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_AWUSER\" :  \"" << m_axi_GMEM_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WVALID\" :  \"" << m_axi_GMEM_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_WREADY\" :  \"" << m_axi_GMEM_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WDATA\" :  \"" << m_axi_GMEM_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WSTRB\" :  \"" << m_axi_GMEM_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WLAST\" :  \"" << m_axi_GMEM_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WID\" :  \"" << m_axi_GMEM_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_WUSER\" :  \"" << m_axi_GMEM_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARVALID\" :  \"" << m_axi_GMEM_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_ARREADY\" :  \"" << m_axi_GMEM_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARADDR\" :  \"" << m_axi_GMEM_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARID\" :  \"" << m_axi_GMEM_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARLEN\" :  \"" << m_axi_GMEM_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARSIZE\" :  \"" << m_axi_GMEM_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARBURST\" :  \"" << m_axi_GMEM_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARLOCK\" :  \"" << m_axi_GMEM_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARCACHE\" :  \"" << m_axi_GMEM_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARPROT\" :  \"" << m_axi_GMEM_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARQOS\" :  \"" << m_axi_GMEM_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARREGION\" :  \"" << m_axi_GMEM_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_ARUSER\" :  \"" << m_axi_GMEM_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RVALID\" :  \"" << m_axi_GMEM_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_RREADY\" :  \"" << m_axi_GMEM_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RDATA\" :  \"" << m_axi_GMEM_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RLAST\" :  \"" << m_axi_GMEM_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RID\" :  \"" << m_axi_GMEM_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RUSER\" :  \"" << m_axi_GMEM_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_RRESP\" :  \"" << m_axi_GMEM_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_BVALID\" :  \"" << m_axi_GMEM_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_GMEM_BREADY\" :  \"" << m_axi_GMEM_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_BRESP\" :  \"" << m_axi_GMEM_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_BID\" :  \"" << m_axi_GMEM_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_GMEM_BUSER\" :  \"" << m_axi_GMEM_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_stream_V_V_TDATA\" :  \"" << sample_stream_V_V_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_stream_V_V_TVALID\" :  \"" << sample_stream_V_V_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_stream_V_V_TREADY\" :  \"" << sample_stream_V_V_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_AWVALID\" :  \"" << s_axi_CTRL_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_AWREADY\" :  \"" << s_axi_CTRL_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_AWADDR\" :  \"" << s_axi_CTRL_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_WVALID\" :  \"" << s_axi_CTRL_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_WREADY\" :  \"" << s_axi_CTRL_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_WDATA\" :  \"" << s_axi_CTRL_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_WSTRB\" :  \"" << s_axi_CTRL_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_ARVALID\" :  \"" << s_axi_CTRL_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_ARREADY\" :  \"" << s_axi_CTRL_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_ARADDR\" :  \"" << s_axi_CTRL_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_RVALID\" :  \"" << s_axi_CTRL_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_RREADY\" :  \"" << s_axi_CTRL_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_RDATA\" :  \"" << s_axi_CTRL_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_RRESP\" :  \"" << s_axi_CTRL_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BVALID\" :  \"" << s_axi_CTRL_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CTRL_BREADY\" :  \"" << s_axi_CTRL_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CTRL_BRESP\" :  \"" << s_axi_CTRL_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

