// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _base_add_HH_
#define _base_add_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "base_add_CTRL_s_axi.h"
#include "base_add_GMEM_m_axi.h"

namespace ap_rtl {

template<unsigned int C_M_AXI_GMEM_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_GMEM_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_DATA_WIDTH = 32,
         unsigned int C_M_AXI_GMEM_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_BUSER_WIDTH = 1,
         unsigned int C_S_AXI_CTRL_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_CTRL_DATA_WIDTH = 32>
struct base_add : public sc_module {
    // Port declarations 68
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > m_axi_GMEM_AWVALID;
    sc_in< sc_logic > m_axi_GMEM_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_ADDR_WIDTH> > m_axi_GMEM_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_GMEM_AWID;
    sc_out< sc_lv<8> > m_axi_GMEM_AWLEN;
    sc_out< sc_lv<3> > m_axi_GMEM_AWSIZE;
    sc_out< sc_lv<2> > m_axi_GMEM_AWBURST;
    sc_out< sc_lv<2> > m_axi_GMEM_AWLOCK;
    sc_out< sc_lv<4> > m_axi_GMEM_AWCACHE;
    sc_out< sc_lv<3> > m_axi_GMEM_AWPROT;
    sc_out< sc_lv<4> > m_axi_GMEM_AWQOS;
    sc_out< sc_lv<4> > m_axi_GMEM_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM_AWUSER_WIDTH> > m_axi_GMEM_AWUSER;
    sc_out< sc_logic > m_axi_GMEM_WVALID;
    sc_in< sc_logic > m_axi_GMEM_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_DATA_WIDTH> > m_axi_GMEM_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM_DATA_WIDTH/8> > m_axi_GMEM_WSTRB;
    sc_out< sc_logic > m_axi_GMEM_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_GMEM_WID;
    sc_out< sc_uint<C_M_AXI_GMEM_WUSER_WIDTH> > m_axi_GMEM_WUSER;
    sc_out< sc_logic > m_axi_GMEM_ARVALID;
    sc_in< sc_logic > m_axi_GMEM_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_ADDR_WIDTH> > m_axi_GMEM_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_GMEM_ARID;
    sc_out< sc_lv<8> > m_axi_GMEM_ARLEN;
    sc_out< sc_lv<3> > m_axi_GMEM_ARSIZE;
    sc_out< sc_lv<2> > m_axi_GMEM_ARBURST;
    sc_out< sc_lv<2> > m_axi_GMEM_ARLOCK;
    sc_out< sc_lv<4> > m_axi_GMEM_ARCACHE;
    sc_out< sc_lv<3> > m_axi_GMEM_ARPROT;
    sc_out< sc_lv<4> > m_axi_GMEM_ARQOS;
    sc_out< sc_lv<4> > m_axi_GMEM_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM_ARUSER_WIDTH> > m_axi_GMEM_ARUSER;
    sc_in< sc_logic > m_axi_GMEM_RVALID;
    sc_out< sc_logic > m_axi_GMEM_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM_DATA_WIDTH> > m_axi_GMEM_RDATA;
    sc_in< sc_logic > m_axi_GMEM_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_GMEM_RID;
    sc_in< sc_uint<C_M_AXI_GMEM_RUSER_WIDTH> > m_axi_GMEM_RUSER;
    sc_in< sc_lv<2> > m_axi_GMEM_RRESP;
    sc_in< sc_logic > m_axi_GMEM_BVALID;
    sc_out< sc_logic > m_axi_GMEM_BREADY;
    sc_in< sc_lv<2> > m_axi_GMEM_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_GMEM_BID;
    sc_in< sc_uint<C_M_AXI_GMEM_BUSER_WIDTH> > m_axi_GMEM_BUSER;
    sc_in< sc_lv<32> > sample_stream_V_V_TDATA;
    sc_in< sc_logic > sample_stream_V_V_TVALID;
    sc_out< sc_logic > sample_stream_V_V_TREADY;
    sc_in< sc_logic > s_axi_CTRL_AWVALID;
    sc_out< sc_logic > s_axi_CTRL_AWREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_ADDR_WIDTH> > s_axi_CTRL_AWADDR;
    sc_in< sc_logic > s_axi_CTRL_WVALID;
    sc_out< sc_logic > s_axi_CTRL_WREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_DATA_WIDTH> > s_axi_CTRL_WDATA;
    sc_in< sc_uint<C_S_AXI_CTRL_DATA_WIDTH/8> > s_axi_CTRL_WSTRB;
    sc_in< sc_logic > s_axi_CTRL_ARVALID;
    sc_out< sc_logic > s_axi_CTRL_ARREADY;
    sc_in< sc_uint<C_S_AXI_CTRL_ADDR_WIDTH> > s_axi_CTRL_ARADDR;
    sc_out< sc_logic > s_axi_CTRL_RVALID;
    sc_in< sc_logic > s_axi_CTRL_RREADY;
    sc_out< sc_uint<C_S_AXI_CTRL_DATA_WIDTH> > s_axi_CTRL_RDATA;
    sc_out< sc_lv<2> > s_axi_CTRL_RRESP;
    sc_out< sc_logic > s_axi_CTRL_BVALID;
    sc_in< sc_logic > s_axi_CTRL_BREADY;
    sc_out< sc_lv<2> > s_axi_CTRL_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<32> > ap_var_for_const2;
    sc_signal< sc_lv<1> > ap_var_for_const3;
    sc_signal< sc_lv<2> > ap_var_for_const5;
    sc_signal< sc_lv<32> > ap_var_for_const7;
    sc_signal< sc_lv<3> > ap_var_for_const4;
    sc_signal< sc_lv<4> > ap_var_for_const6;
    sc_signal< sc_lv<4> > ap_var_for_const8;


    // Module declarations
    base_add(sc_module_name name);
    SC_HAS_PROCESS(base_add);

    ~base_add();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    base_add_CTRL_s_axi<C_S_AXI_CTRL_ADDR_WIDTH,C_S_AXI_CTRL_DATA_WIDTH>* base_add_CTRL_s_axi_U;
    base_add_GMEM_m_axi<0,32,32,5,16,16,16,16,C_M_AXI_GMEM_ID_WIDTH,C_M_AXI_GMEM_ADDR_WIDTH,C_M_AXI_GMEM_DATA_WIDTH,C_M_AXI_GMEM_AWUSER_WIDTH,C_M_AXI_GMEM_ARUSER_WIDTH,C_M_AXI_GMEM_WUSER_WIDTH,C_M_AXI_GMEM_RUSER_WIDTH,C_M_AXI_GMEM_BUSER_WIDTH,C_M_AXI_GMEM_USER_VALUE,C_M_AXI_GMEM_PROT_VALUE,C_M_AXI_GMEM_CACHE_VALUE>* base_add_GMEM_m_axi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > buffer_r;
    sc_signal< sc_lv<32> > sample_count;
    sc_signal< sc_lv<32> > capture_mode;
    sc_signal< sc_lv<32> > sample_stream_V_V_0_data_out;
    sc_signal< sc_logic > sample_stream_V_V_0_vld_in;
    sc_signal< sc_logic > sample_stream_V_V_0_vld_out;
    sc_signal< sc_logic > sample_stream_V_V_0_ack_in;
    sc_signal< sc_logic > sample_stream_V_V_0_ack_out;
    sc_signal< sc_lv<32> > sample_stream_V_V_0_payload_A;
    sc_signal< sc_lv<32> > sample_stream_V_V_0_payload_B;
    sc_signal< sc_logic > sample_stream_V_V_0_sel_rd;
    sc_signal< sc_logic > sample_stream_V_V_0_sel_wr;
    sc_signal< sc_logic > sample_stream_V_V_0_sel;
    sc_signal< sc_logic > sample_stream_V_V_0_load_A;
    sc_signal< sc_logic > sample_stream_V_V_0_load_B;
    sc_signal< sc_lv<2> > sample_stream_V_V_0_state;
    sc_signal< sc_logic > sample_stream_V_V_0_state_cmp_full;
    sc_signal< sc_logic > GMEM_blk_n_AW;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_reg_387;
    sc_signal< sc_logic > GMEM_blk_n_W;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage1;
    sc_signal< bool > ap_block_pp0_stage1;
    sc_signal< sc_lv<1> > exitcond_reg_387_pp0_iter1_reg;
    sc_signal< sc_logic > GMEM_blk_n_B;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_lv<1> > exitcond_reg_387_pp0_iter3_reg;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > exitcond_reg_387_pp0_iter4_reg;
    sc_signal< sc_logic > sample_stream_V_V_TDATA_blk_n;
    sc_signal< sc_lv<1> > tmp_2_reg_383;
    sc_signal< sc_logic > GMEM_AWVALID;
    sc_signal< sc_logic > GMEM_AWREADY;
    sc_signal< sc_lv<32> > GMEM_AWADDR;
    sc_signal< sc_logic > GMEM_WVALID;
    sc_signal< sc_logic > GMEM_WREADY;
    sc_signal< sc_lv<32> > GMEM_WDATA;
    sc_signal< sc_logic > GMEM_ARREADY;
    sc_signal< sc_logic > GMEM_RVALID;
    sc_signal< sc_lv<32> > GMEM_RDATA;
    sc_signal< sc_logic > GMEM_RLAST;
    sc_signal< sc_lv<1> > GMEM_RID;
    sc_signal< sc_lv<1> > GMEM_RUSER;
    sc_signal< sc_lv<2> > GMEM_RRESP;
    sc_signal< sc_logic > GMEM_BVALID;
    sc_signal< sc_logic > GMEM_BREADY;
    sc_signal< sc_lv<2> > GMEM_BRESP;
    sc_signal< sc_lv<1> > GMEM_BID;
    sc_signal< sc_lv<1> > GMEM_BUSER;
    sc_signal< sc_lv<17> > i_reg_158;
    sc_signal< sc_lv<12> > ch2_reg_179;
    sc_signal< sc_lv<31> > tmp_3_cast_fu_199_p1;
    sc_signal< sc_lv<31> > tmp_3_cast_reg_372;
    sc_signal< sc_lv<17> > n_1_fu_231_p3;
    sc_signal< sc_lv<17> > n_1_reg_378;
    sc_signal< sc_lv<1> > tmp_2_fu_239_p2;
    sc_signal< sc_lv<1> > exitcond_fu_245_p2;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_predicate_op50_read_state4;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter1;
    sc_signal< sc_logic > ap_sig_ioackin_GMEM_AWREADY;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter2;
    sc_signal< sc_logic > ap_sig_ioackin_GMEM_WREADY;
    sc_signal< bool > ap_block_state6_io;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter4;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<1> > exitcond_reg_387_pp0_iter2_reg;
    sc_signal< sc_lv<17> > i_1_fu_250_p2;
    sc_signal< sc_lv<17> > i_1_reg_391;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<31> > buffer2_sum_fu_260_p2;
    sc_signal< sc_lv<31> > buffer2_sum_reg_396;
    sc_signal< bool > ap_block_state3_pp0_stage1_iter0;
    sc_signal< bool > ap_block_state5_pp0_stage1_iter1;
    sc_signal< bool > ap_block_state5_io;
    sc_signal< bool > ap_block_state7_pp0_stage1_iter2;
    sc_signal< bool > ap_block_state9_pp0_stage1_iter3;
    sc_signal< bool > ap_block_state11_pp0_stage1_iter4;
    sc_signal< bool > ap_block_pp0_stage1_11001;
    sc_signal< sc_lv<12> > tri_3_fu_291_p3;
    sc_signal< sc_lv<12> > tmp_11_fu_299_p1;
    sc_signal< sc_lv<12> > tmp_9_fu_323_p1;
    sc_signal< sc_lv<31> > buffer2_sum3_fu_347_p2;
    sc_signal< sc_lv<31> > buffer2_sum3_reg_427;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< bool > ap_block_pp0_stage1_subdone;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_lv<17> > ap_phi_mux_i_phi_fu_162_p4;
    sc_signal< sc_lv<12> > ap_phi_reg_pp0_iter0_ch_reg_170;
    sc_signal< sc_lv<12> > ap_phi_reg_pp0_iter1_ch_reg_170;
    sc_signal< sc_lv<12> > ap_phi_reg_pp0_iter0_ch2_reg_179;
    sc_signal< sc_lv<12> > ap_phi_reg_pp0_iter1_ch2_reg_179;
    sc_signal< sc_lv<64> > buffer2_sum_cast_fu_327_p1;
    sc_signal< sc_lv<64> > buffer2_sum3_cast_fu_357_p1;
    sc_signal< sc_logic > ap_reg_ioackin_GMEM_AWREADY;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_logic > ap_reg_ioackin_GMEM_WREADY;
    sc_signal< bool > ap_block_pp0_stage1_01001;
    sc_signal< sc_lv<32> > ch_cast_fu_352_p1;
    sc_signal< sc_lv<32> > ch2_cast_fu_367_p1;
    sc_signal< sc_lv<30> > tmp_3_fu_189_p4;
    sc_signal< sc_lv<1> > tmp_fu_203_p2;
    sc_signal< sc_lv<31> > tmp_4_fu_209_p1;
    sc_signal< sc_lv<31> > p_sample_count_fu_213_p3;
    sc_signal< sc_lv<1> > tmp_1_fu_225_p2;
    sc_signal< sc_lv<17> > tmp_7_fu_221_p1;
    sc_signal< sc_lv<31> > tmp_cast_fu_256_p1;
    sc_signal< sc_lv<8> > phase_fu_265_p1;
    sc_signal< sc_lv<12> > tri_fu_277_p3;
    sc_signal< sc_lv<1> > tmp_10_fu_269_p3;
    sc_signal< sc_lv<12> > tri_1_fu_285_p2;
    sc_signal< sc_lv<11> > p_lshr_f_fu_313_p4;
    sc_signal< sc_lv<17> > tmp_5_fu_337_p2;
    sc_signal< sc_lv<31> > tmp_7_cast_fu_343_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< bool > ap_condition_658;
    sc_signal< bool > ap_condition_662;
    sc_signal< bool > ap_condition_469;
    sc_signal< bool > ap_condition_486;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_pp0_stage0;
    static const sc_lv<4> ap_ST_fsm_pp0_stage1;
    static const sc_lv<4> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM_USER_VALUE;
    static const int C_M_AXI_GMEM_PROT_VALUE;
    static const int C_M_AXI_GMEM_CACHE_VALUE;
    static const int C_M_AXI_DATA_WIDTH;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<31> ap_const_lv31_10000;
    static const sc_lv<17> ap_const_lv17_10000;
    static const sc_lv<17> ap_const_lv17_1;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<12> ap_const_lv12_FF0;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_3;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const7();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const8();
    void thread_ap_clk_no_reset_();
    void thread_GMEM_AWADDR();
    void thread_GMEM_AWVALID();
    void thread_GMEM_BREADY();
    void thread_GMEM_WDATA();
    void thread_GMEM_WVALID();
    void thread_GMEM_blk_n_AW();
    void thread_GMEM_blk_n_B();
    void thread_GMEM_blk_n_W();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_pp0_stage1();
    void thread_ap_block_pp0_stage1_01001();
    void thread_ap_block_pp0_stage1_11001();
    void thread_ap_block_pp0_stage1_subdone();
    void thread_ap_block_state10_pp0_stage0_iter4();
    void thread_ap_block_state11_pp0_stage1_iter4();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage1_iter0();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter1();
    void thread_ap_block_state5_io();
    void thread_ap_block_state5_pp0_stage1_iter1();
    void thread_ap_block_state6_io();
    void thread_ap_block_state6_pp0_stage0_iter2();
    void thread_ap_block_state7_pp0_stage1_iter2();
    void thread_ap_block_state8_pp0_stage0_iter3();
    void thread_ap_block_state9_pp0_stage1_iter3();
    void thread_ap_condition_469();
    void thread_ap_condition_486();
    void thread_ap_condition_658();
    void thread_ap_condition_662();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_i_phi_fu_162_p4();
    void thread_ap_phi_reg_pp0_iter0_ch2_reg_179();
    void thread_ap_phi_reg_pp0_iter0_ch_reg_170();
    void thread_ap_predicate_op50_read_state4();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_ioackin_GMEM_AWREADY();
    void thread_ap_sig_ioackin_GMEM_WREADY();
    void thread_buffer2_sum3_cast_fu_357_p1();
    void thread_buffer2_sum3_fu_347_p2();
    void thread_buffer2_sum_cast_fu_327_p1();
    void thread_buffer2_sum_fu_260_p2();
    void thread_ch2_cast_fu_367_p1();
    void thread_ch_cast_fu_352_p1();
    void thread_exitcond_fu_245_p2();
    void thread_i_1_fu_250_p2();
    void thread_n_1_fu_231_p3();
    void thread_p_lshr_f_fu_313_p4();
    void thread_p_sample_count_fu_213_p3();
    void thread_phase_fu_265_p1();
    void thread_sample_stream_V_V_0_ack_in();
    void thread_sample_stream_V_V_0_ack_out();
    void thread_sample_stream_V_V_0_data_out();
    void thread_sample_stream_V_V_0_load_A();
    void thread_sample_stream_V_V_0_load_B();
    void thread_sample_stream_V_V_0_sel();
    void thread_sample_stream_V_V_0_state_cmp_full();
    void thread_sample_stream_V_V_0_vld_in();
    void thread_sample_stream_V_V_0_vld_out();
    void thread_sample_stream_V_V_TDATA_blk_n();
    void thread_sample_stream_V_V_TREADY();
    void thread_tmp_10_fu_269_p3();
    void thread_tmp_11_fu_299_p1();
    void thread_tmp_1_fu_225_p2();
    void thread_tmp_2_fu_239_p2();
    void thread_tmp_3_cast_fu_199_p1();
    void thread_tmp_3_fu_189_p4();
    void thread_tmp_4_fu_209_p1();
    void thread_tmp_5_fu_337_p2();
    void thread_tmp_7_cast_fu_343_p1();
    void thread_tmp_7_fu_221_p1();
    void thread_tmp_9_fu_323_p1();
    void thread_tmp_cast_fu_256_p1();
    void thread_tmp_fu_203_p2();
    void thread_tri_1_fu_285_p2();
    void thread_tri_3_fu_291_p3();
    void thread_tri_fu_277_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
