-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity base_add is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_GMEM_AWVALID : OUT STD_LOGIC;
    m_axi_GMEM_AWREADY : IN STD_LOGIC;
    m_axi_GMEM_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_GMEM_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_GMEM_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_GMEM_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_GMEM_WVALID : OUT STD_LOGIC;
    m_axi_GMEM_WREADY : IN STD_LOGIC;
    m_axi_GMEM_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_GMEM_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_GMEM_WLAST : OUT STD_LOGIC;
    m_axi_GMEM_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_GMEM_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_GMEM_ARVALID : OUT STD_LOGIC;
    m_axi_GMEM_ARREADY : IN STD_LOGIC;
    m_axi_GMEM_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_GMEM_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_GMEM_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_GMEM_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_GMEM_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_GMEM_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_GMEM_RVALID : IN STD_LOGIC;
    m_axi_GMEM_RREADY : OUT STD_LOGIC;
    m_axi_GMEM_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_GMEM_RLAST : IN STD_LOGIC;
    m_axi_GMEM_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_GMEM_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_GMEM_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_BVALID : IN STD_LOGIC;
    m_axi_GMEM_BREADY : OUT STD_LOGIC;
    m_axi_GMEM_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_GMEM_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_GMEM_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    sample_stream_V_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    sample_stream_V_V_TVALID : IN STD_LOGIC;
    sample_stream_V_V_TREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of base_add is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "base_add,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=65545,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=986,HLS_SYN_LUT=1354,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_10000 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000010000000000000000";
    constant ap_const_lv17_10000 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv12_FF0 : STD_LOGIC_VECTOR (11 downto 0) := "111111110000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal buffer_r : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_count : STD_LOGIC_VECTOR (31 downto 0);
    signal capture_mode : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_stream_V_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_stream_V_V_0_vld_in : STD_LOGIC;
    signal sample_stream_V_V_0_vld_out : STD_LOGIC;
    signal sample_stream_V_V_0_ack_in : STD_LOGIC;
    signal sample_stream_V_V_0_ack_out : STD_LOGIC;
    signal sample_stream_V_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_stream_V_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal sample_stream_V_V_0_sel_rd : STD_LOGIC := '0';
    signal sample_stream_V_V_0_sel_wr : STD_LOGIC := '0';
    signal sample_stream_V_V_0_sel : STD_LOGIC;
    signal sample_stream_V_V_0_load_A : STD_LOGIC;
    signal sample_stream_V_V_0_load_B : STD_LOGIC;
    signal sample_stream_V_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal sample_stream_V_V_0_state_cmp_full : STD_LOGIC;
    signal GMEM_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_reg_387 : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal exitcond_reg_387_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_blk_n_B : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal exitcond_reg_387_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal exitcond_reg_387_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sample_stream_V_V_TDATA_blk_n : STD_LOGIC;
    signal tmp_2_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_AWVALID : STD_LOGIC;
    signal GMEM_AWREADY : STD_LOGIC;
    signal GMEM_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal GMEM_WVALID : STD_LOGIC;
    signal GMEM_WREADY : STD_LOGIC;
    signal GMEM_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal GMEM_ARREADY : STD_LOGIC;
    signal GMEM_RVALID : STD_LOGIC;
    signal GMEM_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal GMEM_RLAST : STD_LOGIC;
    signal GMEM_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal GMEM_BVALID : STD_LOGIC;
    signal GMEM_BREADY : STD_LOGIC;
    signal GMEM_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal GMEM_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal GMEM_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_158 : STD_LOGIC_VECTOR (16 downto 0);
    signal ch2_reg_179 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_cast_fu_199_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_cast_reg_372 : STD_LOGIC_VECTOR (30 downto 0);
    signal n_1_fu_231_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal n_1_reg_378 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op50_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_sig_ioackin_GMEM_AWREADY : STD_LOGIC;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_sig_ioackin_GMEM_WREADY : STD_LOGIC;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond_reg_387_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_250_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal i_1_reg_391 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal buffer2_sum_fu_260_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal buffer2_sum_reg_396 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_state7_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state9_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_state11_pp0_stage1_iter4 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tri_3_fu_291_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_11_fu_299_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_9_fu_323_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal buffer2_sum3_fu_347_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal buffer2_sum3_reg_427 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_phi_mux_i_phi_fu_162_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_phi_reg_pp0_iter0_ch_reg_170 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter1_ch_reg_170 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter0_ch2_reg_179 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter1_ch2_reg_179 : STD_LOGIC_VECTOR (11 downto 0);
    signal buffer2_sum_cast_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal buffer2_sum3_cast_fu_357_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_GMEM_AWREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_reg_ioackin_GMEM_WREADY : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ch_cast_fu_352_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ch2_cast_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_189_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_209_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_sample_count_fu_213_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_221_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_cast_fu_256_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal phase_fu_265_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tri_fu_277_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_10_fu_269_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tri_1_fu_285_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_lshr_f_fu_313_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_fu_337_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_7_cast_fu_343_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_658 : BOOLEAN;
    signal ap_condition_662 : BOOLEAN;
    signal ap_condition_469 : BOOLEAN;
    signal ap_condition_486 : BOOLEAN;

    component base_add_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        buffer_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        sample_count : OUT STD_LOGIC_VECTOR (31 downto 0);
        capture_mode : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component base_add_GMEM_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    base_add_CTRL_s_axi_U : component base_add_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        buffer_r => buffer_r,
        sample_count => sample_count,
        capture_mode => capture_mode);

    base_add_GMEM_m_axi_U : component base_add_GMEM_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_GMEM_AWVALID,
        AWREADY => m_axi_GMEM_AWREADY,
        AWADDR => m_axi_GMEM_AWADDR,
        AWID => m_axi_GMEM_AWID,
        AWLEN => m_axi_GMEM_AWLEN,
        AWSIZE => m_axi_GMEM_AWSIZE,
        AWBURST => m_axi_GMEM_AWBURST,
        AWLOCK => m_axi_GMEM_AWLOCK,
        AWCACHE => m_axi_GMEM_AWCACHE,
        AWPROT => m_axi_GMEM_AWPROT,
        AWQOS => m_axi_GMEM_AWQOS,
        AWREGION => m_axi_GMEM_AWREGION,
        AWUSER => m_axi_GMEM_AWUSER,
        WVALID => m_axi_GMEM_WVALID,
        WREADY => m_axi_GMEM_WREADY,
        WDATA => m_axi_GMEM_WDATA,
        WSTRB => m_axi_GMEM_WSTRB,
        WLAST => m_axi_GMEM_WLAST,
        WID => m_axi_GMEM_WID,
        WUSER => m_axi_GMEM_WUSER,
        ARVALID => m_axi_GMEM_ARVALID,
        ARREADY => m_axi_GMEM_ARREADY,
        ARADDR => m_axi_GMEM_ARADDR,
        ARID => m_axi_GMEM_ARID,
        ARLEN => m_axi_GMEM_ARLEN,
        ARSIZE => m_axi_GMEM_ARSIZE,
        ARBURST => m_axi_GMEM_ARBURST,
        ARLOCK => m_axi_GMEM_ARLOCK,
        ARCACHE => m_axi_GMEM_ARCACHE,
        ARPROT => m_axi_GMEM_ARPROT,
        ARQOS => m_axi_GMEM_ARQOS,
        ARREGION => m_axi_GMEM_ARREGION,
        ARUSER => m_axi_GMEM_ARUSER,
        RVALID => m_axi_GMEM_RVALID,
        RREADY => m_axi_GMEM_RREADY,
        RDATA => m_axi_GMEM_RDATA,
        RLAST => m_axi_GMEM_RLAST,
        RID => m_axi_GMEM_RID,
        RUSER => m_axi_GMEM_RUSER,
        RRESP => m_axi_GMEM_RRESP,
        BVALID => m_axi_GMEM_BVALID,
        BREADY => m_axi_GMEM_BREADY,
        BRESP => m_axi_GMEM_BRESP,
        BID => m_axi_GMEM_BID,
        BUSER => m_axi_GMEM_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => ap_const_logic_0,
        I_ARREADY => GMEM_ARREADY,
        I_ARADDR => ap_const_lv32_0,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_0,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => GMEM_RVALID,
        I_RREADY => ap_const_logic_0,
        I_RDATA => GMEM_RDATA,
        I_RID => GMEM_RID,
        I_RUSER => GMEM_RUSER,
        I_RRESP => GMEM_RRESP,
        I_RLAST => GMEM_RLAST,
        I_AWVALID => GMEM_AWVALID,
        I_AWREADY => GMEM_AWREADY,
        I_AWADDR => GMEM_AWADDR,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_1,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => GMEM_WVALID,
        I_WREADY => GMEM_WREADY,
        I_WDATA => GMEM_WDATA,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => GMEM_BVALID,
        I_BREADY => GMEM_BREADY,
        I_BRESP => GMEM_BRESP,
        I_BID => GMEM_BID,
        I_BUSER => GMEM_BUSER);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_GMEM_AWREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_GMEM_AWREADY <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0)))) then 
                    ap_reg_ioackin_GMEM_AWREADY <= ap_const_logic_0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = GMEM_AWREADY) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = GMEM_AWREADY) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0)))) then 
                    ap_reg_ioackin_GMEM_AWREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ioackin_GMEM_WREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ioackin_GMEM_WREADY <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)))) then 
                    ap_reg_ioackin_GMEM_WREADY <= ap_const_logic_0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = GMEM_WREADY) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = GMEM_WREADY) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)))) then 
                    ap_reg_ioackin_GMEM_WREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    sample_stream_V_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                sample_stream_V_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((sample_stream_V_V_0_ack_out = ap_const_logic_1) and (sample_stream_V_V_0_vld_out = ap_const_logic_1))) then 
                                        sample_stream_V_V_0_sel_rd <= not(sample_stream_V_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    sample_stream_V_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                sample_stream_V_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((sample_stream_V_V_0_ack_in = ap_const_logic_1) and (sample_stream_V_V_0_vld_in = ap_const_logic_1))) then 
                                        sample_stream_V_V_0_sel_wr <= not(sample_stream_V_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    sample_stream_V_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                sample_stream_V_V_0_state <= ap_const_lv2_0;
            else
                if ((((sample_stream_V_V_0_state = ap_const_lv2_2) and (sample_stream_V_V_0_vld_in = ap_const_logic_0)) or ((sample_stream_V_V_0_state = ap_const_lv2_3) and (sample_stream_V_V_0_vld_in = ap_const_logic_0) and (sample_stream_V_V_0_ack_out = ap_const_logic_1)))) then 
                    sample_stream_V_V_0_state <= ap_const_lv2_2;
                elsif ((((sample_stream_V_V_0_state = ap_const_lv2_1) and (sample_stream_V_V_0_ack_out = ap_const_logic_0)) or ((sample_stream_V_V_0_state = ap_const_lv2_3) and (sample_stream_V_V_0_ack_out = ap_const_logic_0) and (sample_stream_V_V_0_vld_in = ap_const_logic_1)))) then 
                    sample_stream_V_V_0_state <= ap_const_lv2_1;
                elsif (((not(((sample_stream_V_V_0_vld_in = ap_const_logic_0) and (sample_stream_V_V_0_ack_out = ap_const_logic_1))) and not(((sample_stream_V_V_0_ack_out = ap_const_logic_0) and (sample_stream_V_V_0_vld_in = ap_const_logic_1))) and (sample_stream_V_V_0_state = ap_const_lv2_3)) or ((sample_stream_V_V_0_state = ap_const_lv2_1) and (sample_stream_V_V_0_ack_out = ap_const_logic_1)) or ((sample_stream_V_V_0_state = ap_const_lv2_2) and (sample_stream_V_V_0_vld_in = ap_const_logic_1)))) then 
                    sample_stream_V_V_0_state <= ap_const_lv2_3;
                else 
                    sample_stream_V_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_ch2_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_reg_383 = ap_const_lv1_0) and (exitcond_reg_387 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_ch2_reg_179 <= sample_stream_V_V_0_data_out(27 downto 16);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_reg_383 = ap_const_lv1_1) and (exitcond_reg_387 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_ch2_reg_179 <= tmp_9_fu_323_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_ch2_reg_179 <= ap_phi_reg_pp0_iter0_ch2_reg_179;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_ch_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_reg_383 = ap_const_lv1_0) and (exitcond_reg_387 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_ch_reg_170 <= tmp_11_fu_299_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_2_reg_383 = ap_const_lv1_1) and (exitcond_reg_387 = ap_const_lv1_0))) then 
                ap_phi_reg_pp0_iter1_ch_reg_170 <= tri_3_fu_291_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_ch_reg_170 <= ap_phi_reg_pp0_iter0_ch_reg_170;
            end if; 
        end if;
    end process;

    i_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0))) then 
                i_reg_158 <= i_1_reg_391;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_158 <= ap_const_lv17_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0))) then
                buffer2_sum3_reg_427 <= buffer2_sum3_fu_347_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (exitcond_reg_387 = ap_const_lv1_0))) then
                buffer2_sum_reg_396 <= buffer2_sum_fu_260_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                ch2_reg_179 <= ap_phi_reg_pp0_iter1_ch2_reg_179;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exitcond_reg_387 <= exitcond_fu_245_p2;
                exitcond_reg_387_pp0_iter1_reg <= exitcond_reg_387;
                exitcond_reg_387_pp0_iter2_reg <= exitcond_reg_387_pp0_iter1_reg;
                exitcond_reg_387_pp0_iter3_reg <= exitcond_reg_387_pp0_iter2_reg;
                exitcond_reg_387_pp0_iter4_reg <= exitcond_reg_387_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                i_1_reg_391 <= i_1_fu_250_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                n_1_reg_378 <= n_1_fu_231_p3;
                tmp_2_reg_383 <= tmp_2_fu_239_p2;
                    tmp_3_cast_reg_372(29 downto 0) <= tmp_3_cast_fu_199_p1(29 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((sample_stream_V_V_0_load_A = ap_const_logic_1)) then
                sample_stream_V_V_0_payload_A <= sample_stream_V_V_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((sample_stream_V_V_0_load_B = ap_const_logic_1)) then
                sample_stream_V_V_0_payload_B <= sample_stream_V_V_TDATA;
            end if;
        end if;
    end process;
    tmp_3_cast_reg_372(30) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter4, exitcond_fu_245_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_fu_245_p2 = ap_const_lv1_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_fu_245_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    GMEM_AWADDR_assign_proc : process(ap_enable_reg_pp0_iter1, buffer2_sum_cast_fu_327_p1, buffer2_sum3_cast_fu_357_p1, ap_reg_ioackin_GMEM_AWREADY, ap_condition_658, ap_condition_662)
    begin
        if (((ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
            if ((ap_const_boolean_1 = ap_condition_662)) then 
                GMEM_AWADDR <= buffer2_sum3_cast_fu_357_p1(32 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_658)) then 
                GMEM_AWADDR <= buffer2_sum_cast_fu_327_p1(32 - 1 downto 0);
            else 
                GMEM_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            GMEM_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GMEM_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_reg_387, ap_CS_fsm_pp0_stage1, exitcond_reg_387_pp0_iter1_reg, ap_reg_ioackin_GMEM_AWREADY, ap_block_pp0_stage0_01001, ap_block_pp0_stage1_01001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0)))) then 
            GMEM_AWVALID <= ap_const_logic_1;
        else 
            GMEM_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    GMEM_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter3_reg, exitcond_reg_387_pp0_iter4_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0)))) then 
            GMEM_BREADY <= ap_const_logic_1;
        else 
            GMEM_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    GMEM_WDATA_assign_proc : process(exitcond_reg_387_pp0_iter1_reg, ap_reg_ioackin_GMEM_WREADY, ch_cast_fu_352_p1, ch2_cast_fu_367_p1, ap_condition_469, ap_condition_486)
    begin
        if (((ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0))) then
            if ((ap_const_boolean_1 = ap_condition_486)) then 
                GMEM_WDATA <= ch2_cast_fu_367_p1;
            elsif ((ap_const_boolean_1 = ap_condition_469)) then 
                GMEM_WDATA <= ch_cast_fu_352_p1;
            else 
                GMEM_WDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            GMEM_WDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    GMEM_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, exitcond_reg_387_pp0_iter1_reg, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_01001, ap_reg_ioackin_GMEM_WREADY, ap_block_pp0_stage1_01001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)))) then 
            GMEM_WVALID <= ap_const_logic_1;
        else 
            GMEM_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    GMEM_blk_n_AW_assign_proc : process(m_axi_GMEM_AWREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_reg_387, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, exitcond_reg_387_pp0_iter1_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0)))) then 
            GMEM_blk_n_AW <= m_axi_GMEM_AWREADY;
        else 
            GMEM_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    GMEM_blk_n_B_assign_proc : process(m_axi_GMEM_BVALID, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter3_reg, exitcond_reg_387_pp0_iter4_reg)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0)))) then 
            GMEM_blk_n_B <= m_axi_GMEM_BVALID;
        else 
            GMEM_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    GMEM_blk_n_W_assign_proc : process(m_axi_GMEM_WREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, exitcond_reg_387_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)))) then 
            GMEM_blk_n_W <= m_axi_GMEM_WREADY;
        else 
            GMEM_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(sample_stream_V_V_0_vld_out, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter3_reg, GMEM_BVALID, ap_predicate_op50_read_state4)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0)) or ((sample_stream_V_V_0_vld_out = ap_const_logic_0) and (ap_predicate_op50_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(sample_stream_V_V_0_vld_out, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter3_reg, ap_enable_reg_pp0_iter2, GMEM_BVALID, ap_predicate_op50_read_state4, ap_block_state4_io, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((sample_stream_V_V_0_vld_out = ap_const_logic_0) and (ap_predicate_op50_read_state4 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(sample_stream_V_V_0_vld_out, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter3_reg, ap_enable_reg_pp0_iter2, GMEM_BVALID, ap_predicate_op50_read_state4, ap_block_state4_io, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state4_io) or ((sample_stream_V_V_0_vld_out = ap_const_logic_0) and (ap_predicate_op50_read_state4 = ap_const_boolean_1)))));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter4_reg, GMEM_BVALID)
    begin
                ap_block_pp0_stage1_01001 <= ((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter4_reg, GMEM_BVALID, ap_block_state5_io)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, exitcond_reg_387_pp0_iter4_reg, GMEM_BVALID, ap_block_state5_io)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_const_logic_0 = GMEM_BVALID) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state10_pp0_stage0_iter4_assign_proc : process(exitcond_reg_387_pp0_iter3_reg, GMEM_BVALID)
    begin
                ap_block_state10_pp0_stage0_iter4 <= ((ap_const_logic_0 = GMEM_BVALID) and (exitcond_reg_387_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_block_state11_pp0_stage1_iter4_assign_proc : process(exitcond_reg_387_pp0_iter4_reg, GMEM_BVALID)
    begin
                ap_block_state11_pp0_stage1_iter4 <= ((ap_const_logic_0 = GMEM_BVALID) and (exitcond_reg_387_pp0_iter4_reg = ap_const_lv1_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(exitcond_reg_387, ap_sig_ioackin_GMEM_AWREADY)
    begin
                ap_block_state4_io <= ((ap_sig_ioackin_GMEM_AWREADY = ap_const_logic_0) and (exitcond_reg_387 = ap_const_lv1_0));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(sample_stream_V_V_0_vld_out, ap_predicate_op50_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((sample_stream_V_V_0_vld_out = ap_const_logic_0) and (ap_predicate_op50_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_io_assign_proc : process(exitcond_reg_387_pp0_iter1_reg, ap_sig_ioackin_GMEM_AWREADY, ap_sig_ioackin_GMEM_WREADY)
    begin
                ap_block_state5_io <= (((ap_sig_ioackin_GMEM_WREADY = ap_const_logic_0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)) or ((ap_sig_ioackin_GMEM_AWREADY = ap_const_logic_0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0)));
    end process;

        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(exitcond_reg_387_pp0_iter1_reg, ap_sig_ioackin_GMEM_WREADY)
    begin
                ap_block_state6_io <= ((ap_sig_ioackin_GMEM_WREADY = ap_const_logic_0) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0));
    end process;

        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_469_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_01001)
    begin
                ap_condition_469 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_486_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_01001)
    begin
                ap_condition_486 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_658_assign_proc : process(ap_CS_fsm_pp0_stage0, exitcond_reg_387, ap_block_pp0_stage0_01001)
    begin
                ap_condition_658 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0));
    end process;


    ap_condition_662_assign_proc : process(ap_CS_fsm_pp0_stage1, exitcond_reg_387_pp0_iter1_reg, ap_block_pp0_stage1_01001)
    begin
                ap_condition_662 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_01001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (exitcond_reg_387_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_fu_245_p2)
    begin
        if ((exitcond_fu_245_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_phi_fu_162_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_reg_387, i_reg_158, i_1_reg_391)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond_reg_387 = ap_const_lv1_0))) then 
            ap_phi_mux_i_phi_fu_162_p4 <= i_1_reg_391;
        else 
            ap_phi_mux_i_phi_fu_162_p4 <= i_reg_158;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_ch2_reg_179 <= "XXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_ch_reg_170 <= "XXXXXXXXXXXX";

    ap_predicate_op50_read_state4_assign_proc : process(exitcond_reg_387, tmp_2_reg_383)
    begin
                ap_predicate_op50_read_state4 <= ((tmp_2_reg_383 = ap_const_lv1_0) and (exitcond_reg_387 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    ap_sig_ioackin_GMEM_AWREADY_assign_proc : process(GMEM_AWREADY, ap_reg_ioackin_GMEM_AWREADY)
    begin
        if ((ap_reg_ioackin_GMEM_AWREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_GMEM_AWREADY <= GMEM_AWREADY;
        else 
            ap_sig_ioackin_GMEM_AWREADY <= ap_const_logic_1;
        end if; 
    end process;


    ap_sig_ioackin_GMEM_WREADY_assign_proc : process(GMEM_WREADY, ap_reg_ioackin_GMEM_WREADY)
    begin
        if ((ap_reg_ioackin_GMEM_WREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_GMEM_WREADY <= GMEM_WREADY;
        else 
            ap_sig_ioackin_GMEM_WREADY <= ap_const_logic_1;
        end if; 
    end process;

    buffer2_sum3_cast_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer2_sum3_reg_427),64));
    buffer2_sum3_fu_347_p2 <= std_logic_vector(unsigned(tmp_7_cast_fu_343_p1) + unsigned(tmp_3_cast_reg_372));
    buffer2_sum_cast_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer2_sum_reg_396),64));
    buffer2_sum_fu_260_p2 <= std_logic_vector(unsigned(tmp_cast_fu_256_p1) + unsigned(tmp_3_cast_reg_372));
    ch2_cast_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ch2_reg_179),32));
    ch_cast_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter1_ch_reg_170),32));
    exitcond_fu_245_p2 <= "1" when (ap_phi_mux_i_phi_fu_162_p4 = n_1_reg_378) else "0";
    i_1_fu_250_p2 <= std_logic_vector(unsigned(ap_phi_mux_i_phi_fu_162_p4) + unsigned(ap_const_lv17_1));
    n_1_fu_231_p3 <= 
        ap_const_lv17_10000 when (tmp_1_fu_225_p2(0) = '1') else 
        tmp_7_fu_221_p1;
    p_lshr_f_fu_313_p4 <= tri_3_fu_291_p3(11 downto 1);
    p_sample_count_fu_213_p3 <= 
        ap_const_lv31_1 when (tmp_fu_203_p2(0) = '1') else 
        tmp_4_fu_209_p1;
    phase_fu_265_p1 <= i_reg_158(8 - 1 downto 0);
    sample_stream_V_V_0_ack_in <= sample_stream_V_V_0_state(1);

    sample_stream_V_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op50_read_state4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op50_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sample_stream_V_V_0_ack_out <= ap_const_logic_1;
        else 
            sample_stream_V_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    sample_stream_V_V_0_data_out_assign_proc : process(sample_stream_V_V_0_payload_A, sample_stream_V_V_0_payload_B, sample_stream_V_V_0_sel)
    begin
        if ((sample_stream_V_V_0_sel = ap_const_logic_1)) then 
            sample_stream_V_V_0_data_out <= sample_stream_V_V_0_payload_B;
        else 
            sample_stream_V_V_0_data_out <= sample_stream_V_V_0_payload_A;
        end if; 
    end process;

    sample_stream_V_V_0_load_A <= (sample_stream_V_V_0_state_cmp_full and not(sample_stream_V_V_0_sel_wr));
    sample_stream_V_V_0_load_B <= (sample_stream_V_V_0_state_cmp_full and sample_stream_V_V_0_sel_wr);
    sample_stream_V_V_0_sel <= sample_stream_V_V_0_sel_rd;
    sample_stream_V_V_0_state_cmp_full <= '0' when (sample_stream_V_V_0_state = ap_const_lv2_1) else '1';
    sample_stream_V_V_0_vld_in <= sample_stream_V_V_TVALID;
    sample_stream_V_V_0_vld_out <= sample_stream_V_V_0_state(0);

    sample_stream_V_V_TDATA_blk_n_assign_proc : process(sample_stream_V_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_reg_387, tmp_2_reg_383)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (tmp_2_reg_383 = ap_const_lv1_0) and (exitcond_reg_387 = ap_const_lv1_0))) then 
            sample_stream_V_V_TDATA_blk_n <= sample_stream_V_V_0_state(0);
        else 
            sample_stream_V_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    sample_stream_V_V_TREADY <= sample_stream_V_V_0_state(1);
    tmp_10_fu_269_p3 <= i_reg_158(7 downto 7);
    tmp_11_fu_299_p1 <= sample_stream_V_V_0_data_out(12 - 1 downto 0);
    tmp_1_fu_225_p2 <= "1" when (unsigned(p_sample_count_fu_213_p3) > unsigned(ap_const_lv31_10000)) else "0";
    tmp_2_fu_239_p2 <= "1" when (capture_mode = ap_const_lv32_0) else "0";
    tmp_3_cast_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_189_p4),31));
    tmp_3_fu_189_p4 <= buffer_r(31 downto 2);
    tmp_4_fu_209_p1 <= sample_count(31 - 1 downto 0);
    tmp_5_fu_337_p2 <= (i_reg_158 xor ap_const_lv17_10000);
    tmp_7_cast_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_337_p2),31));
    tmp_7_fu_221_p1 <= p_sample_count_fu_213_p3(17 - 1 downto 0);
    tmp_9_fu_323_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_lshr_f_fu_313_p4),12));
    tmp_cast_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_158),31));
    tmp_fu_203_p2 <= "1" when (signed(sample_count) < signed(ap_const_lv32_1)) else "0";
    tri_1_fu_285_p2 <= (tri_fu_277_p3 xor ap_const_lv12_FF0);
    tri_3_fu_291_p3 <= 
        tri_1_fu_285_p2 when (tmp_10_fu_269_p3(0) = '1') else 
        tri_fu_277_p3;
    tri_fu_277_p3 <= (phase_fu_265_p1 & ap_const_lv4_0);
end behav;
