// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbase_add.h"

extern XBase_add_Config XBase_add_ConfigTable[];

XBase_add_Config *XBase_add_LookupConfig(u16 DeviceId) {
	XBase_add_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBASE_ADD_NUM_INSTANCES; Index++) {
		if (XBase_add_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBase_add_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBase_add_Initialize(XBase_add *InstancePtr, u16 DeviceId) {
	XBase_add_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBase_add_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBase_add_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

