// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBASE_ADD_H
#define XBASE_ADD_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbase_add_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Ctrl_BaseAddress;
} XBase_add_Config;
#endif

typedef struct {
    u32 Ctrl_BaseAddress;
    u32 IsReady;
} XBase_add;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBase_add_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBase_add_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBase_add_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBase_add_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBase_add_Initialize(XBase_add *InstancePtr, u16 DeviceId);
XBase_add_Config* XBase_add_LookupConfig(u16 DeviceId);
int XBase_add_CfgInitialize(XBase_add *InstancePtr, XBase_add_Config *ConfigPtr);
#else
int XBase_add_Initialize(XBase_add *InstancePtr, const char* InstanceName);
int XBase_add_Release(XBase_add *InstancePtr);
#endif

void XBase_add_Start(XBase_add *InstancePtr);
u32 XBase_add_IsDone(XBase_add *InstancePtr);
u32 XBase_add_IsIdle(XBase_add *InstancePtr);
u32 XBase_add_IsReady(XBase_add *InstancePtr);
void XBase_add_EnableAutoRestart(XBase_add *InstancePtr);
void XBase_add_DisableAutoRestart(XBase_add *InstancePtr);

void XBase_add_Set_buffer_r(XBase_add *InstancePtr, u32 Data);
u32 XBase_add_Get_buffer_r(XBase_add *InstancePtr);
void XBase_add_Set_sample_count(XBase_add *InstancePtr, u32 Data);
u32 XBase_add_Get_sample_count(XBase_add *InstancePtr);
void XBase_add_Set_capture_mode(XBase_add *InstancePtr, u32 Data);
u32 XBase_add_Get_capture_mode(XBase_add *InstancePtr);

void XBase_add_InterruptGlobalEnable(XBase_add *InstancePtr);
void XBase_add_InterruptGlobalDisable(XBase_add *InstancePtr);
void XBase_add_InterruptEnable(XBase_add *InstancePtr, u32 Mask);
void XBase_add_InterruptDisable(XBase_add *InstancePtr, u32 Mask);
void XBase_add_InterruptClear(XBase_add *InstancePtr, u32 Mask);
u32 XBase_add_InterruptGetEnabled(XBase_add *InstancePtr);
u32 XBase_add_InterruptGetStatus(XBase_add *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
