// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of buffer_r
//        bit 31~0 - buffer_r[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of sample_count
//        bit 31~0 - sample_count[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of capture_mode
//        bit 31~0 - capture_mode[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBASE_ADD_CTRL_ADDR_AP_CTRL           0x00
#define XBASE_ADD_CTRL_ADDR_GIE               0x04
#define XBASE_ADD_CTRL_ADDR_IER               0x08
#define XBASE_ADD_CTRL_ADDR_ISR               0x0c
#define XBASE_ADD_CTRL_ADDR_BUFFER_R_DATA     0x10
#define XBASE_ADD_CTRL_BITS_BUFFER_R_DATA     32
#define XBASE_ADD_CTRL_ADDR_SAMPLE_COUNT_DATA 0x18
#define XBASE_ADD_CTRL_BITS_SAMPLE_COUNT_DATA 32
#define XBASE_ADD_CTRL_ADDR_CAPTURE_MODE_DATA 0x20
#define XBASE_ADD_CTRL_BITS_CAPTURE_MODE_DATA 32

